// Explicit migrator/fixture seed declaration. Runtime callers never write global taxonomy.
// Official TMDB OpenAPI observed examples, with independently reviewed English translations.
export const MOVIE_GENRE_SEED_PROVENANCE={source:'https://developer.themoviedb.org/openapi/tmdb-api.json',observed:'2026-10-03',movieExampleSha256:'274cd3014c427d14d017be17ef0405be0f5fbd8c8cc9d026482c7dda5af12737',tvExampleSha256:'f6d789ca6ccc2c0d348f804a8a4e2c87485cceefe25ecffd0feff3f10937cf50',labels:'independently-reviewed-English-translations',liveProviderQualified:false} as const;
export const MOVIE_GENRE_SEEDS=[
 {externalKind:'movie',providerGenreId:28,label:'Action',slug:'action'},
 {externalKind:'movie',providerGenreId:12,label:'Adventure',slug:'adventure'},
 {externalKind:'movie',providerGenreId:16,label:'Animation',slug:'animation'},
 {externalKind:'movie',providerGenreId:35,label:'Comedy',slug:'comedy'},
 {externalKind:'movie',providerGenreId:80,label:'Crime',slug:'crime'},
 {externalKind:'movie',providerGenreId:99,label:'Documentary',slug:'documentary'},
 {externalKind:'movie',providerGenreId:18,label:'Drama',slug:'drama'},
 {externalKind:'movie',providerGenreId:10751,label:'Family',slug:'family'},
 {externalKind:'movie',providerGenreId:14,label:'Fantasy',slug:'fantasy'},
 {externalKind:'movie',providerGenreId:36,label:'History',slug:'history'},
 {externalKind:'movie',providerGenreId:27,label:'Horror',slug:'horror'},
 {externalKind:'movie',providerGenreId:10402,label:'Music',slug:'music'},
 {externalKind:'movie',providerGenreId:9648,label:'Mystery',slug:'mystery'},
 {externalKind:'movie',providerGenreId:10749,label:'Romance',slug:'romance'},
 {externalKind:'movie',providerGenreId:878,label:'Science Fiction',slug:'science-fiction'},
 {externalKind:'movie',providerGenreId:10770,label:'TV Movie',slug:'tv-movie'},
 {externalKind:'movie',providerGenreId:53,label:'Thriller',slug:'thriller'},
 {externalKind:'movie',providerGenreId:10752,label:'War',slug:'war'},
 {externalKind:'movie',providerGenreId:37,label:'Western',slug:'western'},
 {externalKind:'tv',providerGenreId:10759,label:'Action & Adventure',slug:'action-adventure'},
 {externalKind:'tv',providerGenreId:16,label:'Animation',slug:'animation'},
 {externalKind:'tv',providerGenreId:35,label:'Comedy',slug:'comedy'},
 {externalKind:'tv',providerGenreId:80,label:'Crime',slug:'crime'},
 {externalKind:'tv',providerGenreId:99,label:'Documentary',slug:'documentary'},
 {externalKind:'tv',providerGenreId:18,label:'Drama',slug:'drama'},
 {externalKind:'tv',providerGenreId:10751,label:'Family',slug:'family'},
 {externalKind:'tv',providerGenreId:10762,label:'Kids',slug:'kids'},
 {externalKind:'tv',providerGenreId:9648,label:'Mystery',slug:'mystery'},
 {externalKind:'tv',providerGenreId:10763,label:'News',slug:'news'},
 {externalKind:'tv',providerGenreId:10764,label:'Reality',slug:'reality'},
 {externalKind:'tv',providerGenreId:10765,label:'Sci-Fi & Fantasy',slug:'sci-fi-fantasy'},
 {externalKind:'tv',providerGenreId:10766,label:'Soap',slug:'soap'},
 {externalKind:'tv',providerGenreId:10767,label:'Talk',slug:'talk'},
 {externalKind:'tv',providerGenreId:10768,label:'War & Politics',slug:'war-politics'},
 {externalKind:'tv',providerGenreId:37,label:'Western',slug:'western'},
] as const;
