import type {Pool,PoolClient} from 'pg';
import {movieDetailsSchema,movieEntityDtoSchema,movieContextSchema,movieTermsSchema,type MovieDetails,type MovieContext} from '../../shared/explorersMovieContract';
import {RecommendationFailure} from './explorersRecommendationRepository';
export async function insertMovieDetails(db:PoolClient,id:string,d:MovieDetails){await db.query(`INSERT INTO movie_entity_details(entity_id,media_type,original_title,year_text,poster_url,backdrop_url,genres,director,runtime_minutes,provider_rating,overview,season_count,watch_providers,cast_details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb)`,[id,d.mediaType,d.originalTitle,d.yearText,d.posterUrl,d.backdropUrl,d.genres.map(g=>g.name),d.director,d.runtimeMinutes,d.providerRating,d.overview,d.seasonCount,JSON.stringify(d.watchProviders),JSON.stringify(d.cast)]);for(let position=0;position<d.genres.length;position++)await db.query('INSERT INTO movie_entity_provider_genres(entity_id,position,provider_genre_id,name) VALUES($1,$2,$3,$4)',[id,position,d.genres[position].providerGenreId,d.genres[position].name]);}
export async function readMovieEntity(db:Pick<Pool,'query'>,id:string){const bound=(await db.query('SELECT octet_length(to_json(d)::text) bytes FROM movie_entity_details d WHERE entity_id=$1',[id])).rows[0];if(Number(bound?.bytes??0)>1048576)throw new RecommendationFailure(413,'Movie facts too large');const r=(await db.query(`SELECT e.id,e.kind,e.title,e.origin,e.facts_version,d.*,i.external_kind,i.external_id,i.fetched_at,i.source_url FROM entities e JOIN movie_entity_details d ON d.entity_id=e.id LEFT JOIN entity_identifiers i ON i.entity_id=e.id AND i.provider='tmdb' WHERE e.id=$1`,[id])).rows[0];if(!r)throw new RecommendationFailure(404,'Movie detail unavailable');const genres=(await db.query('SELECT provider_genre_id,name FROM movie_entity_provider_genres WHERE entity_id=$1 ORDER BY position',[id])).rows.map(g=>({providerGenreId:Number(g.provider_genre_id),name:g.name}));return movieEntityDtoSchema.parse({id:r.id,kind:r.kind,title:r.title,origin:r.origin,details:{mediaType:r.media_type,originalTitle:r.original_title,yearText:r.year_text,posterUrl:r.poster_url,backdropUrl:r.backdrop_url,genres,director:r.director,runtimeMinutes:r.runtime_minutes,providerRating:r.provider_rating===null?null:Number(r.provider_rating),overview:r.overview,seasonCount:r.season_count,watchProviders:r.watch_providers,cast:r.cast_details},provenance:r.external_id?{provider:'tmdb',externalKind:r.external_kind,externalId:r.external_id,fetchedAt:new Date(r.fetched_at).getTime(),sourceUrl:r.source_url,mappingVersion:Number(r.facts_version)}:null});}
export async function readMovieContext(db:Pick<Pool,'query'>,id:string,account:string){const row=(await db.query('SELECT region,selected_provider_ids FROM movie_recommendation_context WHERE recommendation_id=$1 AND account_id=$2',[id,account])).rows[0];return movieContextSchema.parse({region:row?.region??'US',selectedProviderIds:row?.selected_provider_ids?.map(Number)??null});}
export function effectiveMovieDetails(d:MovieDetails,overrides:Record<string,unknown>){const v={...d};for(const key of Object.keys(d))if(Object.hasOwn(overrides,key))(v as any)[key]=overrides[key];return movieDetailsSchema.parse(v);}
export async function checkMovieContext(db:PoolClient,entity:string,context:MovieContext){const c=movieContextSchema.parse(context);const d=(await readMovieEntity(db,entity)).details;const ids=c.selectedProviderIds;if(ids?.length){const r=d.watchProviders[c.region];const actual=new Set(r?[...r.flatrate,...r.rent,...r.buy].map(p=>p.providerId):[]);if(ids.some(id=>!actual.has(id)))throw new RecommendationFailure(422,'MOVIE_CONTEXT_INCOMPATIBLE');}}
export async function writeMovieContext(db:PoolClient,id:string,account:string,entity:string,context:MovieContext){await checkMovieContext(db,entity,context);await db.query(`INSERT INTO movie_recommendation_context(recommendation_id,account_id,region,selected_provider_ids) VALUES($1,$2,$3,$4) ON CONFLICT(recommendation_id) DO UPDATE SET region=excluded.region,selected_provider_ids=excluded.selected_provider_ids`,[id,account,context.region,context.selectedProviderIds]);}
export async function writeMovieTerms(db:PoolClient,id:string,account:string,entity:string,terms?:string[]){let ids=terms;if(ids===undefined){const row=(await db.query('SELECT media_type FROM movie_entity_details WHERE entity_id=$1',[entity])).rows[0];const mapped=await db.query(`SELECT g.provider_genre_id,m.term_id FROM movie_entity_provider_genres g LEFT JOIN movie_provider_genre_terms m ON m.external_kind=$2 AND m.provider_genre_id=g.provider_genre_id WHERE g.entity_id=$1 ORDER BY g.position`,[entity,row?.media_type]);if(mapped.rows.some(r=>!r.term_id))throw new RecommendationFailure(422,'MOVIE_GENRE_MAPPING_UNAVAILABLE');ids=Array.from(new Set(mapped.rows.map(r=>r.term_id as string)));}if(ids.length>32||new Set(ids).size!==ids.length)throw new RecommendationFailure(422,'Invalid Movie genre selection');for(const term of ids)if(!(await db.query("SELECT 1 FROM taxonomy_terms WHERE id=$1 AND category='movies' AND active=true",[term])).rows[0])throw new RecommendationFailure(422,'Movie genre unavailable');await db.query('DELETE FROM recommendation_taxonomy WHERE recommendation_id=$1 AND account_id=$2',[id,account]);for(let position=0;position<ids.length;position++)await db.query("INSERT INTO recommendation_taxonomy(recommendation_id,account_id,category,term_id,position) VALUES($1,$2,'movies',$3,$4)",[id,account,ids[position],position]);}

export async function readMovieTerms(db:Pick<Pool,'query'>,id:string,account:string){const rows=(await db.query(`SELECT t.id,t.category,t.slug,x.label,r.position FROM recommendation_taxonomy r JOIN taxonomy_terms t ON t.id=r.term_id AND t.category=r.category JOIN taxonomy_term_translations x ON x.term_id=t.id AND x.locale='en' WHERE r.recommendation_id=$1 AND r.account_id=$2 AND r.category='movies' ORDER BY r.position LIMIT 33`,[id,account])).rows;return movieTermsSchema.parse(rows);}
