import {describe,it,expect,vi,beforeEach} from 'vitest';
import {render,screen,waitFor,act,fireEvent} from '@testing-library/react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import AddBookPage, {InlineSearch} from '../AddBookPage';
import useAuthStore from '../../../../../store/store';
import {explorersApiClient} from '../../../../../lib/explorersApiClient';
import {emptyBookDetails} from '../../../../../../../tunes/shared/explorersBookContract';
const state=vi.hoisted(()=>({content:undefined as any}));
vi.mock('../../../api/useBooksOwnerContent',()=>({useBooksOwnerContent:()=>state.content}));
vi.mock('../../../../Favorites/components/TiptapEditor',()=>({default:({value,onChange}:any)=><textarea aria-label="Recommendation note" value={value} onChange={e=>onChange(e.target.value)}/>}));
vi.mock('../../../../../lib/explorersApiClient',()=>({explorersApiClient:{updateMyRecommendation:vi.fn(),getMyEditableRecommendation:vi.fn(),getCompleteMyCategoryTopPicks:vi.fn(),setMyCategoryTopPicks:vi.fn(),createMedia:vi.fn(),searchBookCandidates:vi.fn(),resolveBookEntity:vi.fn(),getMyEditableCollection:vi.fn(),createMyRecommendation:vi.fn(),importBookCovers:vi.fn()}}));
vi.mock('sonner',()=>({toast:{error:vi.fn(),success:vi.fn(),info:vi.fn()}}));
const observation={detail:{id:'rec',revision:1}};
const loaded=()=>({data:{bookLists:[{recommended_books:[{documentId:'rec',entity_id:'entity',title:'Hydrated book',authors:[],subjects:[],Media:[],volume_id:'volume',user_recommendation_note:'<p>Original</p>'}]}]},content:{observation:{generation:2},details:new Map([['rec',observation]])}});
function form(){return <MemoryRouter initialEntries={['/books/list/edit/rec']}><Routes><Route path="/books/:listId/edit/:bookId" element={<AddBookPage/>}/><Route path="/recommendations/books/:listId" element={<p>Saved list</p>}/></Routes></MemoryRouter>;}
describe('actual canonical Add/edit form',()=>{
 beforeEach(()=>{vi.clearAllMocks();useAuthStore.setState({generation:2,accountId:'owner'});state.content=loaded();vi.mocked(explorersApiClient.getMyEditableRecommendation).mockResolvedValue({detail:{id:'rec',revision:2}} as never);vi.mocked(explorersApiClient.getCompleteMyCategoryTopPicks).mockResolvedValue({topPicks:[]} as never);vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:vi.fn(()=> 'blob:fixture'),revokeObjectURL:vi.fn()}));});
 it('holds interactive fields until hydration and saves captured revision',async()=>{state.content={};const view=render(form());expect(screen.queryByLabelText('Recommendation note')).toBeNull();state.content=loaded();view.rerender(form());fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'<p>Edited</p>'}});fireEvent.click(screen.getByRole('button',{name:'Save Changes'}));await screen.findByText('Saved list');expect(explorersApiClient.updateMyRecommendation).toHaveBeenCalledWith(observation,expect.objectContaining({note:{version:1,format:'quill-html',html:'<p>Edited</p>'}}),expect.any(String),expect.any(AbortSignal));});
 it('retains draft on snapshot upload failure',async()=>{vi.mocked(explorersApiClient.createMedia).mockRejectedValue(new Error('Upload failed'));const view=render(form());fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'Keep draft'}});fireEvent.change(view.container.querySelector('input[type=file]')!,{target:{files:[new File(['image'],'snapshot.png',{type:'image/png'})]}});fireEvent.click(screen.getByRole('button',{name:'Save Changes'}));await waitFor(()=>expect(explorersApiClient.createMedia).toHaveBeenCalled());expect(explorersApiClient.updateMyRecommendation).not.toHaveBeenCalled();expect(screen.getByLabelText('Recommendation note')).toHaveValue('Keep draft');expect(screen.queryByText('Saved list')).toBeNull();});
 it('aborts upload and clears old form when generation changes',async()=>{let resolveUpload:(value:any)=>void=()=>{};vi.mocked(explorersApiClient.createMedia).mockImplementation(()=>new Promise(resolve=>{resolveUpload=resolve;}));const view=render(form());await screen.findByLabelText('Recommendation note');fireEvent.change(view.container.querySelector('input[type=file]')!,{target:{files:[new File(['image'],'snapshot.png',{type:'image/png'})]}});fireEvent.click(screen.getByRole('button',{name:'Save Changes'}));await waitFor(()=>expect(explorersApiClient.createMedia).toHaveBeenCalled());const signal=vi.mocked(explorersApiClient.createMedia).mock.calls[0][2];await act(async()=>{useAuthStore.setState({generation:3,accountId:'other'});resolveUpload({id:'media'});});expect(signal?.aborted).toBe(true);expect(explorersApiClient.updateMyRecommendation).not.toHaveBeenCalled();expect(screen.queryByLabelText('Recommendation note')).toBeNull();expect(screen.queryByText('Saved list')).toBeNull();});
 it('reuses a partially created recommendation and saves current fields on retry',async()=>{
  vi.mocked(explorersApiClient.searchBookCandidates).mockResolvedValue({items:[{title:'Fixture',provider:'google_books',externalKind:'volume',externalId:'volume',preview:emptyBookDetails(),buyLinkSuggestion:null}],nextCursor:null} as never);
  vi.mocked(explorersApiClient.resolveBookEntity).mockResolvedValue({id:'00000000-0000-4000-8000-000000000003'} as never);
  vi.mocked(explorersApiClient.getMyEditableCollection).mockResolvedValue({collection:{id:'list',revision:1}} as never);
  vi.mocked(explorersApiClient.createMyRecommendation).mockResolvedValue({id:'rec'} as never);
  vi.mocked(explorersApiClient.importBookCovers).mockResolvedValue({slots:{cover:{status:'copied'},thumbnail:{status:'copied'}}} as never);
  vi.mocked(explorersApiClient.setMyCategoryTopPicks).mockRejectedValueOnce(new Error('Pin conflict')).mockResolvedValue(undefined as never);
  render(<MemoryRouter initialEntries={['/books/list/add']}><Routes><Route path="/books/:listId/add" element={<AddBookPage/>}/><Route path="/recommendations/books/:listId" element={<p>Saved list</p>}/></Routes></MemoryRouter>);
  fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'fixture'}});fireEvent.click(await screen.findByRole('button',{name:/^Fixture/}));fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'Initial draft'}});fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await waitFor(()=>expect(explorersApiClient.setMyCategoryTopPicks).toHaveBeenCalledTimes(1));await waitFor(()=>expect(screen.getByRole('button',{name:'Add to List'})).toBeEnabled());
  fireEvent.change(screen.getByLabelText('Recommendation note'),{target:{value:'Changed after failure'}});fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await screen.findByText('Saved list');expect(explorersApiClient.createMyRecommendation).toHaveBeenCalledTimes(1);expect(explorersApiClient.updateMyRecommendation).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({note:{version:1,format:'quill-html',html:'Changed after failure'}}),expect.any(String),expect.any(AbortSignal));
 });
});

describe('round1 Books regressions',()=>{
 beforeEach(()=>{vi.clearAllMocks();useAuthStore.setState({generation:2,accountId:'owner'});state.content=loaded();});
 it.each(['', 'https://legacy.invalid/api'])('keeps canonical edit snapshot URL with legacy REST %s',async(host)=>{vi.stubEnv('VITE_REST_API_URL',host);state.content.data.bookLists[0].recommended_books[0].Media=[{documentId:'media',url:'/api/explorers/v1/media/media/content'}];const view=render(form());await screen.findByLabelText('Recommendation note');expect(view.container.querySelector('img[src*="media/content"]')?.getAttribute('src')).toBe('/api/explorers/v1/media/media/content');});
 it('replays unknown create with identical command and patches changed draft',async()=>{
  vi.mocked(explorersApiClient.searchBookCandidates).mockResolvedValue({items:[{title:'Fixture',provider:'google_books',externalKind:'volume',externalId:'volume',preview:emptyBookDetails(),buyLinkSuggestion:null}],nextCursor:null} as never);vi.mocked(explorersApiClient.resolveBookEntity).mockResolvedValue({id:'00000000-0000-4000-8000-000000000003'} as never);vi.mocked(explorersApiClient.getMyEditableCollection).mockResolvedValue({collection:{id:'list',revision:1}} as never);vi.mocked(explorersApiClient.createMyRecommendation).mockRejectedValueOnce(new Error('Lost acknowledgment')).mockResolvedValue({id:'rec'} as never);vi.mocked(explorersApiClient.getMyEditableRecommendation).mockResolvedValue({detail:{id:'rec',revision:2}} as never);vi.mocked(explorersApiClient.getCompleteMyCategoryTopPicks).mockResolvedValue({topPicks:[]} as never);vi.mocked(explorersApiClient.setMyCategoryTopPicks).mockResolvedValue(undefined as never);vi.mocked(explorersApiClient.importBookCovers).mockResolvedValue({slots:{cover:{status:'copied'},thumbnail:{status:'copied'}}} as never);
  render(<MemoryRouter initialEntries={['/books/list/add']}><Routes><Route path="/books/:listId/add" element={<AddBookPage/>}/><Route path="/recommendations/books/:listId" element={<p>Saved list</p>}/></Routes></MemoryRouter>);fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'fixture'}});fireEvent.click(await screen.findByRole('button',{name:/^Fixture/}));fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'Original command'}});fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await waitFor(()=>expect(explorersApiClient.createMyRecommendation).toHaveBeenCalledTimes(1));await waitFor(()=>expect(screen.getByRole('button',{name:'Add to List'})).toBeEnabled());fireEvent.change(screen.getByLabelText('Recommendation note'),{target:{value:'Changed draft'}});fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await screen.findByText('Saved list');const calls=vi.mocked(explorersApiClient.createMyRecommendation).mock.calls;expect(calls[1].slice(0,3)).toEqual(calls[0].slice(0,3));expect(explorersApiClient.getMyEditableCollection).toHaveBeenCalledTimes(1);expect(explorersApiClient.updateMyRecommendation).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({note:expect.objectContaining({html:'Changed draft'})}),expect.any(String),expect.any(AbortSignal));
 });
 it.each(['query','generation','unmount'])('ignores delayed continuation after %s changes',async(kind)=>{
  let settle:(value:any)=>void=()=>{};const candidate=(title:string)=>({title,externalId:title,preview:emptyBookDetails()});vi.mocked(explorersApiClient.searchBookCandidates).mockImplementation(async(input:any)=>input.cursor?await new Promise(resolve=>{settle=resolve;}):({items:[candidate(input.query)],nextCursor:'next'} as never));const view=render(<InlineSearch onSelect={()=>{}}/>);fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'Original'}});await screen.findByText('Original');fireEvent.click(screen.getByRole('button',{name:'Load more books'}));await waitFor(()=>expect(explorersApiClient.searchBookCandidates).toHaveBeenCalledTimes(2));const signal=vi.mocked(explorersApiClient.searchBookCandidates).mock.calls[1][1];if(kind==='query'){fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'Current'}});await screen.findByText('Current');}else if(kind==='generation'){await act(async()=>useAuthStore.setState({generation:3,accountId:'other'}));await waitFor(()=>expect(explorersApiClient.searchBookCandidates).toHaveBeenCalledTimes(3));}else view.unmount();await act(async()=>settle({items:[candidate('Obsolete continuation')],nextCursor:'obsolete'}));expect(signal?.aborted).toBe(true);expect(screen.queryByText('Obsolete continuation')).toBeNull();if(kind==='query')expect(screen.getByText('Current')).toBeVisible();
 });
});
it('obsolete continuation rejection cannot clear a pending new query or set its error',async()=>{
 useAuthStore.setState({generation:2,accountId:'owner'});vi.clearAllMocks();let rejectOld:(reason:any)=>void=()=>{},resolveCurrent:(value:any)=>void=()=>{};vi.mocked(explorersApiClient.searchBookCandidates).mockImplementation((input:any)=>input.cursor?new Promise((_resolve,reject)=>{rejectOld=reject;}):input.query==='Current'?new Promise(resolve=>{resolveCurrent=resolve;}):Promise.resolve({items:[{title:'Original',externalId:'original',preview:emptyBookDetails()}],nextCursor:'next'} as never));render(<InlineSearch onSelect={()=>{}}/>);fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'Original'}});await screen.findByText('Original');fireEvent.click(screen.getByRole('button',{name:'Load more books'}));await waitFor(()=>expect(explorersApiClient.searchBookCandidates).toHaveBeenCalledTimes(2));fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'Current'}});await waitFor(()=>expect(explorersApiClient.searchBookCandidates).toHaveBeenCalledTimes(3));await act(async()=>rejectOld(new Error('Obsolete failure')));expect(screen.queryByRole('alert')).toBeNull();expect(screen.queryByText('No results found for "Current"')).toBeNull();await act(async()=>resolveCurrent({items:[{title:'Current',externalId:'current',preview:emptyBookDetails()}],nextCursor:null}));expect(screen.getByText('Current')).toBeVisible();expect(screen.queryByRole('button',{name:'Load more books'})).toBeNull();
});
it('corrects an unsent invalid URL and then creates through the actual canonical client',async()=>{
 const real=await vi.importActual<typeof import('../../../../../lib/explorersApiClient')>('../../../../../lib/explorersApiClient');const owner='00000000-0000-4000-8000-000000000001',list='00000000-0000-4000-8000-000000000002',entity='00000000-0000-4000-8000-000000000003',rec='00000000-0000-4000-8000-000000000004';vi.clearAllMocks();useAuthStore.setState({generation:2,accountId:owner,isAuthenticated:true});state.content={};const sent:any[]=[];vi.stubGlobal('fetch',async(_url:string,options:RequestInit)=>{if(!options.method)return new Response(JSON.stringify({collection:{id:list,accountId:owner,category:'books',title:'List',slug:'list',visibility:'private',publicationState:'draft',revision:1,description:null,heading:null,coverMediaId:null,archived:false,displayOrder:0,categoryRevision:'1'}}));sent.push(JSON.parse(options.body as string));return new Response(JSON.stringify({recommendation:{id:rec,accountId:owner,category:'books',entityId:entity,userRating:null,publicationState:'published',revision:1,mediaIds:[]}}),{status:201});});vi.mocked(explorersApiClient.getMyEditableCollection).mockImplementation(real.explorersApiClient.getMyEditableCollection);vi.mocked(explorersApiClient.createMyRecommendation).mockImplementation(real.explorersApiClient.createMyRecommendation);vi.mocked(explorersApiClient.searchBookCandidates).mockResolvedValue({items:[{title:'Fixture',provider:'google_books',externalKind:'volume',externalId:'volume',preview:emptyBookDetails(),buyLinkSuggestion:null}],nextCursor:null} as never);vi.mocked(explorersApiClient.resolveBookEntity).mockResolvedValue({id:entity} as never);vi.mocked(explorersApiClient.getMyEditableRecommendation).mockResolvedValue({detail:{id:rec,revision:2}} as never);vi.mocked(explorersApiClient.importBookCovers).mockResolvedValue({slots:{cover:{status:'copied'},thumbnail:{status:'copied'}}} as never);vi.mocked(explorersApiClient.getCompleteMyCategoryTopPicks).mockResolvedValue({topPicks:[]} as never);vi.mocked(explorersApiClient.setMyCategoryTopPicks).mockResolvedValue(undefined as never);
 const view=render(<MemoryRouter initialEntries={[`/books/${list}/add`]}><Routes><Route path="/books/:listId/add" element={<AddBookPage/>}/><Route path="/recommendations/books/:listId" element={<p>Saved list</p>}/></Routes></MemoryRouter>);fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'fixture'}});fireEvent.click(await screen.findByRole('button',{name:/^Fixture/}));await screen.findByLabelText('Recommendation note');fireEvent.change(screen.getByPlaceholderText('https://...'),{target:{value:'http://example.com:8080/book'}});fireEvent.click(screen.getByRole('button',{name:'Add link'}));fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Add to List'})).toBeEnabled());expect(sent).toHaveLength(0);const invalid=screen.getByText('http://example.com:8080/book',{exact:false});fireEvent.click(invalid.parentElement!.querySelector('button')!);fireEvent.change(screen.getByPlaceholderText('https://...'),{target:{value:'https://example.com/book'}});fireEvent.click(screen.getByRole('button',{name:'Add link'}));fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await screen.findByText('Saved list');expect(sent).toHaveLength(1);expect(sent[0].bookContext.buyLinks).toEqual([{name:'Link',url:'https://example.com/book'}]);view.unmount();vi.unstubAllGlobals();
});