import {it,expect,vi} from 'vitest';
import {MovieCatalog,mapMovieDetail} from '../services/movieCatalog';
import {movieContextSchema,movieDetailsSchema} from '../../shared/explorersMovieContract';
const item=(id:number)=>({id,title:`Movie ${id}`,name:`Show ${id}`,poster_path:null,release_date:null,first_air_date:null});
const actor={accountId:'a',userId:'u',role:'owner' as const,credential:{kind:'web-session' as const,sessionId:'s',sessionVersion:1}};
const list=(n:number,start=1,page=1,total=2)=>({page,total_pages:total,total_results:500,results:Array.from({length:n},(_,i)=>item(start+i))});
it('preserves mixed remainder and equal movie/TV identifiers',async()=>{const f=vi.fn(async(u:any)=>{const page=Number(new URL(String(u)).searchParams.get("page"));return new Response(JSON.stringify(list(20,1+(page-1)*20,page)));});const c=new MovieCatalog({accessToken:'fixture',fetch:f,authorize:async()=>{},now:()=>1000});const a=await c.search(actor,{query:'title',limit:24});expect(a.items).toHaveLength(24);expect(a.items[0]).toMatchObject({externalKind:'movie',externalId:'1'});expect(a.items[1]).toMatchObject({externalKind:'tv',externalId:'1'});const b=await c.search(actor,{query:'title',limit:24,cursor:a.nextCursor});expect(b.items.slice(0,16).map(x=>`${x.externalKind}:${x.externalId}`)).toEqual(Array.from({length:16},(_,i)=>`${i%2?'tv':'movie'}:${13+Math.floor(i/2)}`));expect(f.mock.calls.every(([u])=>String(u).includes('include_adult=false'))).toBe(true);});
for(const n of [21,100,101])it(`bounds upstream envelope ${n}`,async()=>{const c=new MovieCatalog({accessToken:'fixture',fetch:async()=>new Response(JSON.stringify(list(n,1,1,1))),authorize:async()=>{}});if(n<=100)expect((await c.search(actor,{query:'x',mediaType:'movie'})).items).toHaveLength(Math.min(n,24));else await expect(c.search(actor,{query:'x',mediaType:'movie'})).rejects.toMatchObject({status:502});});
it('reauthorizes replay and post-I/O',async()=>{let allowed=true;const authorize=vi.fn(async()=>{if(!allowed)throw Error('REVOKED');});const f=vi.fn(async()=>new Response(JSON.stringify(list(100))));const c=new MovieCatalog({accessToken:'x',fetch:f,authorize});const a=await c.search(actor,{query:'x',mediaType:'movie',limit:1});await c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor});allowed=false;await expect(c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor})).rejects.toThrow('REVOKED');allowed=true;f.mockImplementation(async()=>{allowed=false;return new Response(JSON.stringify(list(20)));});await expect(c.search(actor,{query:'new'})).rejects.toThrow('REVOKED');});
it('bounds stalled body/nonsettling cancellation',async()=>{const c=new MovieCatalog({accessToken:'private',deadlineMs:20,fetch:async()=>new Response(new ReadableStream({start(){},cancel(){return new Promise(()=>{});}})),authorize:async()=>{}});await expect(c.search(actor,{query:'x'})).rejects.toMatchObject({status:503,message:'Movie provider unavailable'});});
it('preserves zero/null and rejects forged identity/context',()=>{const raw={id:42,title:'Title',original_title:'Original',release_date:null,poster_path:null,backdrop_path:null,genres:[],runtime:0,vote_average:0,overview:null,credits:{cast:[],crew:[]}};const a=mapMovieDetail(raw,'movie','42',1000,{});expect(a.details).toMatchObject({runtimeMinutes:0,yearText:null,providerRating:0,seasonCount:null});expect(()=>mapMovieDetail({...raw,id:43},'movie','42',1000,{})).toThrow();expect(movieDetailsSchema.safeParse({...a.details,watchSelection:[1]}).success).toBe(false);for(const ids of [[1,1],[null],[Number.MAX_SAFE_INTEGER+1]])expect(movieContextSchema.safeParse({region:'US',selectedProviderIds:ids}).success).toBe(false);expect(movieContextSchema.parse({region:'US',selectedProviderIds:null}).selectedProviderIds).toBeNull();expect(movieContextSchema.parse({region:'US',selectedProviderIds:[]}).selectedProviderIds).toEqual([]);});

it('singleflight returns exact same-token response and saved response is mutation isolated',async()=>{const f=vi.fn(async(u:any)=>{const page=Number(new URL(String(u)).searchParams.get('page'));return new Response(JSON.stringify(list(100,1+(page-1)*100,page,5)));});const c=new MovieCatalog({accessToken:'x',fetch:f,authorize:async()=>{}});const a=await c.search(actor,{query:'x',mediaType:'movie',limit:1});const [b,d]=await Promise.all([c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor}),c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor})]);expect(b).toEqual(d);expect(f).toHaveBeenCalledTimes(1);b.items[0].title='MUTATED';expect((await c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor})).items[0].title).not.toBe('MUTATED');});
it('cursor conflict/expiry never silently starts new page',async()=>{let now=1000;const f=vi.fn(async()=>new Response(JSON.stringify(list(100))));const c=new MovieCatalog({accessToken:'x',fetch:f,authorize:async()=>{},now:()=>now});const a=await c.search(actor,{query:'x',limit:1});for(const patch of [{query:'z'},{limit:2},{mediaType:'movie' as const}])await expect(c.search(actor,{query:'x',limit:1,cursor:a.nextCursor,...patch})).rejects.toMatchObject({status:410});now+=600001;await expect(c.search(actor,{query:'x',limit:1,cursor:a.nextCursor})).rejects.toMatchObject({status:410});expect(f).toHaveBeenCalledTimes(2);});
it('failed second-source request exposes no partial success and retry starts first page',async()=>{let broken=true;const f=vi.fn(async(u:any)=>String(u).includes('/tv')&&broken?new Response('{}',{status:503}):new Response(JSON.stringify(list(20))));const c=new MovieCatalog({accessToken:'x',fetch:f,authorize:async()=>{}});await expect(c.search(actor,{query:'x'})).rejects.toMatchObject({status:503});broken=false;expect((await c.search(actor,{query:'x'})).items[0].externalId).toBe('1');expect(f).toHaveBeenCalledTimes(4);});
it('accepts valid later shrinking totals and rejects contradictory early empty page',async()=>{const f=vi.fn(async(u:any)=>{const page=Number(new URL(String(u)).searchParams.get('page'));return new Response(JSON.stringify(page===1?list(1,1,1,3):list(0,1,page,0)));});const c=new MovieCatalog({accessToken:'x',fetch:f,authorize:async()=>{}});const a=await c.search(actor,{query:'x',mediaType:'movie',limit:1});expect((await c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor})).nextCursor).toBeNull();const d=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async()=>new Response(JSON.stringify(list(0,1,1,3)))});await expect(d.search(actor,{query:'x'})).rejects.toMatchObject({status:502});});
it('counts failed requests for quota and never echoes private upstream messages',async()=>{const f=vi.fn(async()=>new Response('private upstream secret',{status:503}));const c=new MovieCatalog({accessToken:'secret-token',fetch:f,authorize:async()=>{}});for(let i=0;i<30;i++)await expect(c.search(actor,{query:'x'})).rejects.toMatchObject({message:'Movie provider unavailable'});await expect(c.search(actor,{query:'x'})).rejects.toMatchObject({status:429});expect(f).toHaveBeenCalledTimes(30);});
it('whole-page deadline also bounds authority revalidation',async()=>{const f=vi.fn();const c=new MovieCatalog({accessToken:'x',deadlineMs:15,fetch:f,authorize:()=>new Promise(()=>{})});await expect(c.search(actor,{query:'x'})).rejects.toMatchObject({status:503});expect(f).not.toHaveBeenCalled();});
it('rejects malformed UTF8, excess bytes/depth and HTTP redirects, using fixed origin',async()=>{const responses=[new Response(Uint8Array.of(0xff,0xfe)),new Response('x'.repeat(2097153)),new Response(JSON.stringify({page:1,total_pages:1,total_results:1,results:[item(1)],nested:Array.from({length:18}).reduce((x)=>({x}),{} as any)})),new Response('{}',{status:302,headers:{Location:'https://evil.invalid/?secret'}})];for(const response of responses){const f=vi.fn(async(u:any,opts:any)=>{expect(new URL(String(u)).origin).toBe('https://api.themoviedb.org');expect(opts.redirect).toBe('error');return response;});const c=new MovieCatalog({accessToken:'x',fetch:f,authorize:async()=>{}});await expect(c.search(actor,{query:'x'})).rejects.toBeInstanceOf(Error);}});
it('distinct actor fairness preserves authority and permits no caller-supplied provider metadata',async()=>{const c=new MovieCatalog({accessToken:'x',fetch:async()=>new Response(JSON.stringify(list(100))),authorize:async()=>{}});for(let i=0;i<20;i++)await c.search(actor,{query:String(i),limit:1});expect((await c.search(actor,{query:'overflow',limit:1})).items).toHaveLength(1);expect(Array.from((c as any).states.values()).filter((e:any)=>e.state.account===actor.accountId)).toHaveLength(20);expect((await c.search({...actor,accountId:'b'},{query:'fresh',limit:1})).items).toHaveLength(1);await expect(c.search(actor,{query:'x',provider:'evil'})).rejects.toMatchObject({status:422});});


it('expiry during upstream I/O denies response and does not publish an expired continuation',async()=>{let now=1000;const c=new MovieCatalog({accessToken:'x',now:()=>now,authorize:async()=>{},fetch:async()=>{now=601001;return new Response(JSON.stringify(list(100)));}});await expect(c.search(actor,{query:'x',mediaType:'movie',limit:1})).rejects.toMatchObject({status:410,code:'CURSOR_EXPIRED'});});

it('rejects duplicate and escaped-equivalent provider keys rather than accepting overwritten identities',async()=>{for(const body of ['{"page":99,"page":1,"total_pages":1,"total_results":0,"results":[]}','{"page":99,"p\\u0061ge":1,"total_pages":1,"total_results":0,"results":[]}']){const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async()=>new Response(body)});await expect(c.search(actor,{query:'x',mediaType:'movie'})).rejects.toMatchObject({status:502});}});

it('accounts large tentative mixed-source queues before final authority and releases peak reservations',async()=>{let c:MovieCatalog;let peak=0;c=new MovieCatalog({accessToken:'x',authorize:async()=>{peak=Math.max(peak,(c as any).inflight);},fetch:async()=>new Response(JSON.stringify({...list(100),results:Array.from({length:100},(_,i)=>({...item(i+1),title:'m'.repeat(1000),name:'t'.repeat(1000),poster_path:'/'+ 'p'.repeat(200)}))}))});await c.search(actor,{query:'x',limit:1});expect(peak).toBeGreaterThan(262144);expect((c as any).inflight).toBe(0);});

it('charges raw candidate scans even when an upstream envelope is rejected',async()=>{let broken=false;const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async()=>new Response(JSON.stringify(broken?list(101,101,2,4):list(1,1,1,4)))});const a=await c.search(actor,{query:'x',mediaType:'movie',limit:1});broken=true;await expect(c.search(actor,{query:'x',mediaType:'movie',limit:1,cursor:a.nextCursor})).rejects.toMatchObject({status:502});expect([...((c as any).states.values())][0].state.lineage.scans).toBe(102);});

it('rejects provider detail titles beyond the canonical500-character persistence boundary',()=>{const raw={id:42,title:'m'.repeat(501),genres:[],credits:{cast:[],crew:[]}};expect(()=>mapMovieDetail(raw,'movie','42',1000,{})).toThrow();expect(mapMovieDetail({...raw,title:'m'.repeat(500)},'movie','42',1000,{}).title).toHaveLength(500);});

it('accounts for retained detail and watch bodies through finalActor authorization and releases them afterwards',async()=>{let c:MovieCatalog;const retained:number[]=[];c=new MovieCatalog({accessToken:'x',authorize:async()=>{retained.push((c as any).inflight);},fetch:async(u:any)=>new Response(JSON.stringify(String(u).includes('/watch/providers')?{id:42,results:{}}:{id:42,title:'T',genres:[],credits:{cast:[],crew:[]},overview:'x'.repeat(1000)}))});await c.resolve(actor,'movie','42');expect(retained.at(-1)).toBeGreaterThan(2000);expect((c as any).inflight).toBe(0);});

it('reports an explicit continuation limit instead of falsely asserting upstream exhaustion at500',async()=>{const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async(u:any)=>{const page=Number(new URL(String(u)).searchParams.get('page'));return new Response(JSON.stringify(list(100,1+(page-1)*100,page,500)));}});let cursor:string|undefined;for(let page=0;page<20;page++){const r=await c.search(actor,{query:'finite',mediaType:'movie',limit:24,...(cursor?{cursor}:{})});cursor=r.nextCursor??undefined;expect(cursor).toBeDefined();}await expect(c.search(actor,{query:'finite',mediaType:'movie',limit:24,cursor})).rejects.toMatchObject({status:429,code:'CONTINUATION_LIMIT'});});

it('charges cached replay quota and preserves another account admission',async()=>{const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async()=>new Response(JSON.stringify(list(100)))});const first=await c.search(actor,{query:'quota',mediaType:'movie',limit:1});for(let i=0;i<29;i++)await c.search(actor,{query:'quota',mediaType:'movie',limit:1,cursor:first.nextCursor});await expect(c.search(actor,{query:'quota',mediaType:'movie',limit:1,cursor:first.nextCursor})).rejects.toMatchObject({status:429,code:'RATE_LIMITED'});expect((await c.search({...actor,accountId:'independent'},{query:'quota',mediaType:'movie',limit:1})).items).toHaveLength(1);});
it('bounds four active provider pages and one per account without blocking later independent progress',async()=>{let release:()=>void=()=>{};const gate=new Promise<void>(r=>{release=r;});const f=vi.fn(async()=>{await gate;return new Response(JSON.stringify(list(1,1,1,1)));});const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:f});const jobs=Array.from({length:4},(_,i)=>c.search({...actor,accountId:'a'+i},{query:'slots',mediaType:'movie'}));for(let i=0;i<100&&f.mock.calls.length<4;i++)await Promise.resolve();expect(f).toHaveBeenCalledTimes(4);await expect(c.search({...actor,accountId:'fifth'},{query:'slots',mediaType:'movie'})).rejects.toMatchObject({status:429});await expect(c.search({...actor,accountId:'a0'},{query:'other',mediaType:'movie'})).rejects.toMatchObject({status:429});release();expect(await Promise.all(jobs)).toHaveLength(4);expect((await c.search({...actor,accountId:'fifth'},{query:'slots',mediaType:'movie'})).items).toHaveLength(1);expect((c as any).inflight).toBe(0);});

it('evicts least recently used unprotected account state and returns410 for its opaque cursor',async()=>{const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async()=>new Response(JSON.stringify(list(100)))});const cursors:string[]=[];for(let i=0;i<20;i++)cursors.push((await c.search(actor,{query:'q'+i,mediaType:'movie',limit:1})).nextCursor!);await c.search(actor,{query:'q0',mediaType:'movie',limit:1,cursor:cursors[0]});const fresh=await c.search(actor,{query:'fresh',mediaType:'movie',limit:1});expect(fresh.nextCursor).not.toBeNull();await expect(c.search(actor,{query:'q1',mediaType:'movie',limit:1,cursor:cursors[1]})).rejects.toMatchObject({status:410,code:'CURSOR_EXPIRED'});expect((await c.search(actor,{query:'q0',mediaType:'movie',limit:1,cursor:cursors[0]})).items).toHaveLength(1);});
it('keeps four timed-out noncooperative transports owned until they really settle',async()=>{const pending:Array<(r:Response)=>void>=[];const c=new MovieCatalog({accessToken:'x',deadlineMs:20,authorize:async()=>{},fetch:async()=>new Promise<Response>(r=>pending.push(r))});const outcomes=await Promise.all(Array.from({length:4},(_,i)=>c.search({...actor,accountId:'detached'+i},{query:'x',mediaType:'movie'}).catch(e=>e)));expect(outcomes.every(e=>e.status===503)).toBe(true);expect(pending).toHaveLength(4);await expect(c.search({...actor,accountId:'fifth'},{query:'x',mediaType:'movie'})).rejects.toMatchObject({status:429,code:'RATE_LIMITED'});expect(pending).toHaveLength(4);for(const finish of pending)finish(new Response('{}'));for(let i=0;i<30;i++)await Promise.resolve();expect((c as any).active).toBe(0);expect((c as any).inflight).toBe(0);});

it('protects a busy oldest cursor while global LRU evicts an eligible peer',async()=>{let release:()=>void=()=>{};let started=false;const gate=new Promise<void>(r=>{release=r;});const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async(u:any)=>{const url=new URL(String(u));const page=Number(url.searchParams.get('page'));if(url.searchParams.get('query')==='busy'&&page===2){started=true;await gate;}return new Response(JSON.stringify(list(1,page,page,500)));}});const first=await c.search(actor,{query:'busy',mediaType:'movie',limit:1});const job=c.search(actor,{query:'busy',mediaType:'movie',limit:1,cursor:first.nextCursor});for(let i=0;i<100&&!started;i++)await Promise.resolve();expect(started).toBe(true);for(let i=0;i<200;i++)await c.search({...actor,accountId:'peer'+i},{query:'peer',mediaType:'movie',limit:1});expect((c as any).states.has(first.nextCursor)).toBe(true);release();const response=await job;expect(response.items).toHaveLength(1);expect(await c.search(actor,{query:'busy',mediaType:'movie',limit:1,cursor:first.nextCursor})).toEqual(response);expect((c as any).states.size).toBeLessThanOrEqual(200);});
it('quarantines stalled cancellation after caller deadline and releases only on settlement',async()=>{let cancelDone:()=>void=()=>{};const cancelled=new Promise<void>(r=>{cancelDone=r;});const c=new MovieCatalog({accessToken:'x',deadlineMs:20,authorize:async()=>{},fetch:async()=>new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(1024));},cancel(){return cancelled;}}))});await expect(c.search(actor,{query:'stalled',mediaType:'movie'})).rejects.toMatchObject({status:503});expect((c as any).active).toBe(1);expect((c as any).inflight).toBeGreaterThan(262144);await expect(c.search(actor,{query:'retry',mediaType:'movie'})).rejects.toMatchObject({status:429});cancelDone();for(let i=0;i<30;i++)await Promise.resolve();expect((c as any).active).toBe(0);expect((c as any).inflight).toBe(0);});

it('reports true exhaustion at500 only when both upstream queues and page sources are exhausted',async()=>{const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async(u:any)=>{const page=Number(new URL(String(u)).searchParams.get('page'));return new Response(JSON.stringify(list(100,1+(page-1)*100,page,5)));}});let cursor:string|undefined;for(let page=0;page<20;page++){const r=await c.search(actor,{query:'complete',mediaType:'movie',limit:24,...(cursor?{cursor}:{})});cursor=r.nextCursor??undefined;}const last=await c.search(actor,{query:'complete',mediaType:'movie',limit:24,cursor});expect(last.items).toHaveLength(20);expect(last.nextCursor).toBeNull();});

it('retains failed-response body cancellation ownership after HTTP rejection',async()=>{let settle:()=>void=()=>{};const cancellation=new Promise<void>(r=>{settle=r;});const c=new MovieCatalog({accessToken:'x',authorize:async()=>{},fetch:async()=>new Response(new ReadableStream({cancel(){return cancellation;}}),{status:500})});await expect(c.search(actor,{query:'failure',mediaType:'movie'})).rejects.toMatchObject({status:503});expect((c as any).active).toBe(1);await expect(c.search(actor,{query:'retry',mediaType:'movie'})).rejects.toMatchObject({status:429});settle();for(let i=0;i<30;i++)await Promise.resolve();expect((c as any).active).toBe(0);expect((c as any).inflight).toBe(0);});
