import {describe,it,expect} from 'vitest';
import {assertSelectedCollectionPlan} from './owner-content-plan-assertion';
const owner='11111111-1111-4111-8111-111111111111',collection='22222222-2222-4222-8222-222222222222';
const metrics={'Actual Loops':1,'Rows Removed by Filter':0,'Rows Removed by Index Recheck':0,'Temp Read Blocks':0,'Temp Written Blocks':0};
const scan=(relation:string,alias:string,index:string,rows:number,loops:number,condition:string)=>({...metrics,'Node Type':'Index Scan','Relation Name':relation,Alias:alias,'Index Name':index,'Scan Direction':'Forward','Actual Rows':rows,'Actual Loops':loops,'Index Cond':condition,Filter:`((account_id = '${owner}'::uuid) AND (category = 'books'::text))`});
const plan=()=>({'Node Type':'Limit',...metrics,'Actual Rows':25,Plans:[{'Node Type':'Incremental Sort',...metrics,'Actual Rows':25,'Sort Key':['i.display_order','r.id'],'Presorted Key':['i.display_order'],'Full-sort Groups':{'Group Count':1,'Sort Methods Used':['quicksort'],'Sort Space Memory':{'Average Sort Space Used':28,'Peak Sort Space Used':28}},Plans:[{'Node Type':'Nested Loop',...metrics,'Join Type':'Inner','Inner Unique':true,'Actual Rows':26,Plans:[scan('collection_items','i','collection_items_collection_id_display_order_key',26,1,`(collection_id = '${collection}'::uuid)`),scan('recommendations','r','recommendations_pkey',1,26,'(id = i.recommendation_id)')]}]}]});
const context={accountId:owner,category:'books',collectionId:collection};
describe('selected collection bounded query-plan contract',()=>{
 it('accepts the exact observed unique-order alternative',()=>expect(()=>assertSelectedCollectionPlan(plan(),context)).not.toThrow());
 it('retains the matching owner index path with owner predicates in index conditions',()=>{const p=plan(),outer=p.Plans[0].Plans[0].Plans[0];outer['Index Name']='collection_items_owner_collection_order_idx';outer['Index Cond']+=` AND (account_id = '${owner}'::uuid) AND (category = 'books'::text)`;delete (outer as any).Filter;expect(()=>assertSelectedCollectionPlan(p,context)).not.toThrow();});
 for(const [label,mutate] of Object.entries({wrongIndex:(p:any)=>p.Plans[0].Plans[0].Plans[0]['Index Name']='unrelated_idx',wrongCollection:(p:any)=>p.Plans[0].Plans[0].Plans[0]['Index Cond']='(collection_id = NULL)',missingOwner:(p:any)=>p.Plans[0].Plans[0].Plans[0].Filter="(category = 'books'::text)",wrongOwner:(p:any)=>p.Plans[0].Plans[0].Plans[1].Filter=`(account_id = '${collection}'::uuid) AND (category = 'books'::text)`,missingCategory:(p:any)=>p.Plans[0].Plans[0].Plans[1].Filter=`(account_id = '${owner}'::uuid)`,orBypass:(p:any)=>p.Plans[0].Plans[0].Plans[0].Filter+=' OR true',outerWork:(p:any)=>p.Plans[0].Plans[0].Plans[0]['Actual Rows']=1000,innerWork:(p:any)=>p.Plans[0].Plans[0].Plans[1]['Actual Loops']=1000,filterWork:(p:any)=>p.Plans[0].Plans[0].Plans[1]['Rows Removed by Filter']=1,recheckWork:(p:any)=>p.Plans[0].Plans[0].Plans[0]['Rows Removed by Index Recheck']=1,seqScan:(p:any)=>p.Plans[0].Plans[0].Plans[0]['Node Type']='Seq Scan',fullSort:(p:any)=>p.Plans[0]['Node Type']='Sort',wrongOrder:(p:any)=>p.Plans[0]['Sort Key']=['r.id'],missingPresort:(p:any)=>p.Plans[0]['Presorted Key']=[],sortWork:(p:any)=>p.Plans[0]['Full-sort Groups']['Group Count']=10,sortMemory:(p:any)=>p.Plans[0]['Full-sort Groups']['Sort Space Memory']['Peak Sort Space Used']=10000,spill:(p:any)=>p.Plans[0]['Temp Written Blocks']=1,limit:(p:any)=>p['Actual Rows']=24,materialize:(p:any)=>p.Plans[0].Plans[0].Plans.push({'Node Type':'Materialize'}),wrongJoin:(p:any)=>p.Plans[0].Plans[0].Plans[1]['Index Cond']='(id = r.id)',missingFilterMetric:(p:any)=>delete p.Plans[0].Plans[0].Plans[1]['Rows Removed by Filter'],joinFilterWork:(p:any)=>p.Plans[0].Plans[0]['Rows Removed by Join Filter']=1,missingMetrics:(p:any)=>delete p.Plans[0].Plans[0].Plans[1]['Actual Loops']}))it('rejects '+label,()=>{const p=plan();mutate(p);expect(()=>assertSelectedCollectionPlan(p,context)).toThrow();});
});
