import {movieEntityDtoSchema,movieDetailsSchema,movieContextSchema,movieTermsSchema,movieDisplayFieldsSchema} from './explorersMovieContract';
import {bookCoversSchema} from './explorersBookCoverContract';
import { z } from 'zod/v3';
import { collectionCoreDtoSchema, recommendationCoreDtoSchema, contentCategorySchema, contentIdSchema, topPickCategorySchema,entityCoreDtoSchema,displayOverridesReadSchema,catalogTitleSchema } from './explorersContract';
import { richNoteSchema } from './explorersRichNoteContract';
import {bookEntityDtoSchema,bookEntityDetailsSchema,bookRecommendationContextSchema,bookDisplayFieldsSchema} from './explorersBookContract';
const status=z.enum(['active','archived','all']).default('active');
const token=z.string().min(1).max(4096);
const limit=z.union([z.number().int().min(1).max(100),z.string().regex(/^[1-9][0-9]{0,2}$/).transform(Number).pipe(z.number().max(100))]).default(24);
export const ownerCollectionsRequestSchema=z.object({category:contentCategorySchema,status,limit,cursor:token.optional(),snapshotToken:token.optional()}).strict();
export const ownerRecommendationsRequestSchema=ownerCollectionsRequestSchema.extend({collectionId:contentIdSchema.optional()}).strict();
export const ownerDetailRequestSchema=z.object({status}).strict();
export const ownerCollectionDtoSchema=collectionCoreDtoSchema.extend({title:z.string().min(1).max(200),description:z.string().nullable(),heading:z.string().nullable(),archived:z.boolean(),displayOrder:z.number().int().nonnegative()}).strict();
export const ownerRecommendationDtoSchema=recommendationCoreDtoSchema.extend({archived:z.boolean(),pin:z.object({collectionId:contentIdSchema,position:z.number().int().nonnegative(),revision:z.number().int().positive().safe()}).strict().nullable()}).strict();
const revision=z.string().regex(/^(0|[1-9][0-9]{0,15})$/).refine(v=>Number.isSafeInteger(Number(v)));
export const editableOwnerCollectionSchema=ownerCollectionDtoSchema.extend({categoryRevision:revision}).strict();
export const editableOwnerRecommendationSchema=ownerRecommendationDtoSchema.extend({categoryRevision:revision,bookCovers:bookCoversSchema.optional(),note:richNoteSchema.nullable(),entity:z.union([entityCoreDtoSchema,bookEntityDtoSchema,movieEntityDtoSchema]),displayOverrides:displayOverridesReadSchema,displayTitle:catalogTitleSchema.nullable(),bookContext:bookRecommendationContextSchema.optional(),effectiveBookDetails:bookEntityDetailsSchema.optional(),movieContext:movieContextSchema.optional(),effectiveMovieDetails:movieDetailsSchema.optional(),movieTerms:movieTermsSchema.optional()}).strict().superRefine((v,ctx)=>{
 const expected={places:['place','person'],movies:['movie'],books:['book'],games:['game'],apps:['app'],products:['product'],people:['person']};
 const title=Object.prototype.hasOwnProperty.call(v.displayOverrides,'title')?v.displayOverrides.title:v.entity.title;
 if(v.entity.id!==v.entityId||!expected[v.category].includes(v.entity.kind)||v.displayTitle!==title)ctx.addIssue({code:'custom',message:'Inconsistent catalog presentation'});
 if(v.category!=='books'&&(v.bookCovers!==undefined||v.bookContext!==undefined||v.effectiveBookDetails!==undefined))ctx.addIssue({code:'custom',message:'Inconsistent Book presentation'});
 if(v.category!=='movies'&&(v.movieContext!==undefined||v.effectiveMovieDetails!==undefined||v.movieTerms!==undefined))ctx.addIssue({code:'custom',message:'Inconsistent Movie presentation'});
 const {title:_title,...fields}=v.displayOverrides;
 if(v.category==='books'?!bookDisplayFieldsSchema.safeParse(fields).success:v.category==='movies'?!movieDisplayFieldsSchema.safeParse(fields).success:Object.keys(fields).length>0)ctx.addIssue({code:'custom',message:'Inconsistent category overrides'});
 if('details' in v.entity){
  const effective=v.entity.kind==='book'?v.effectiveBookDetails:v.effectiveMovieDetails;
  if(v.entity.kind==='book'?v.category!=='books'||!v.bookContext||!effective:v.category!=='movies'||!v.movieContext||!v.movieTerms||!effective)ctx.addIssue({code:'custom',message:'Missing typed presentation'});
  else for(const [key,value] of Object.entries(v.entity.details))if(JSON.stringify((effective as any)[key])!==JSON.stringify(Object.prototype.hasOwnProperty.call(v.displayOverrides,key)?(v.displayOverrides as any)[key]:value))ctx.addIssue({code:'custom',message:'Inconsistent effective details'});
 }
});
export type EditableOwnerCollection=z.infer<typeof editableOwnerCollectionSchema>;
export type EditableOwnerRecommendation=z.infer<typeof editableOwnerRecommendationSchema>;
export const ownerSnapshotRequestSchema=z.object({category:contentCategorySchema,snapshotToken:token.optional()}).strict();
export const ownerSnapshotValidationRequestSchema=ownerSnapshotRequestSchema.extend({snapshotToken:token}).strict();
export const ownerSnapshotSchema=z.object({version:z.literal('explorers-owner-content/v2'),snapshotToken:token,revision,expiresAt:z.number().int().positive(),pinRevision:z.number().int().positive().safe().nullable()}).strict();
export const ownerMembershipsRequestSchema=z.object({category:contentCategorySchema,collectionStatus:status,recommendationStatus:status,recommendationId:contentIdSchema.optional(),limit,cursor:token.optional(),snapshotToken:token.optional()}).strict();
export const ownerMembershipDtoSchema=z.object({recommendationId:contentIdSchema,collectionId:contentIdSchema,collectionRevision:z.number().int().positive().safe(),displayOrder:z.number().int().nonnegative(),collectionArchived:z.boolean(),recommendationArchived:z.boolean()}).strict();
export const ownerCollectionPageSchema=z.object({version:z.literal('explorers-owner-content/v2'),snapshot:revision,snapshotToken:token,expiresAt:z.number().int().positive(),items:z.array(ownerCollectionDtoSchema).max(100),nextCursor:token.nullable()}).strict();
export const ownerRecommendationPageSchema=ownerCollectionPageSchema.extend({items:z.array(ownerRecommendationDtoSchema).max(100)}).strict();
export const ownerMembershipPageSchema=ownerCollectionPageSchema.extend({items:z.array(ownerMembershipDtoSchema).max(100)}).strict();
export const ownerTopPicksRequestSchema=z.object({category:topPickCategorySchema,limit,cursor:token.optional(),snapshotToken:token.optional()}).strict();
export const ownerTopPickDtoSchema=z.object({recommendationId:contentIdSchema,collectionId:contentIdSchema,position:z.number().int().nonnegative()}).strict();
export const ownerTopPickPageSchema=ownerCollectionPageSchema.extend({pinRevision:z.number().int().positive().safe().nullable(),items:z.array(ownerTopPickDtoSchema).max(100)}).strict();
export type OwnerTopPicksRequest=z.input<typeof ownerTopPicksRequestSchema>;
export type OwnerCollectionsRequest=z.input<typeof ownerCollectionsRequestSchema>;
export type OwnerRecommendationsRequest=z.input<typeof ownerRecommendationsRequestSchema>;
export type OwnerCollectionDto=z.infer<typeof ownerCollectionDtoSchema>;
export type OwnerRecommendationDto=z.infer<typeof ownerRecommendationDtoSchema>;
export type OwnerCollectionPage=z.infer<typeof ownerCollectionPageSchema>;
export type OwnerRecommendationPage=z.infer<typeof ownerRecommendationPageSchema>;
export type OwnerMembershipsRequest=z.input<typeof ownerMembershipsRequestSchema>;
export type OwnerMembershipDto=z.infer<typeof ownerMembershipDtoSchema>;
export type OwnerMembershipPage=z.infer<typeof ownerMembershipPageSchema>;
export type OwnerSnapshot=z.infer<typeof ownerSnapshotSchema>;
