import { z } from 'zod/v3';
import {contentCategorySchema,contentIdSchema,entityCoreDtoSchema} from './explorersContract';
import {publicRecommendationSummarySchema} from './explorersPublicContentContract';
export const SEARCH_PAGE_BYTES=4*1024*1024;
const token=z.string().min(1).max(4096);
const query=z.string().trim().refine(v=>Array.from(v).length<=200&&new TextEncoder().encode(v).length<=800&&!/[\u0000-\u001f\u007f]/.test(v)&&!/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(v),'Invalid search query').default('');
const ids=z.array(contentIdSchema.transform(v=>v.toLowerCase())).max(100).refine(v=>new Set(v).size===v.length,'Duplicate entity').transform(v=>v.sort());
const fields={category:contentCategorySchema,query,entityIds:ids.optional(),collectionId:contentIdSchema.transform(v=>v.toLowerCase()).optional(),limit:z.union([z.number().int().min(1).max(100),z.string().regex(/^[1-9][0-9]{0,2}$/).transform(Number).pipe(z.number().max(100))]).default(24),cursor:token.optional()};
export const ownerSearchRequestSchema=z.object({...fields,scope:z.literal('owner'),snapshotToken:token.optional()}).strict();
export const publicSearchRequestSchema=z.object({...fields,scope:z.literal('public'),creatorHandle:z.string().trim().toLowerCase().regex(/^[a-z][a-z0-9-]{2,29}$/).optional()}).strict();
export const searchRequestSchema=z.discriminatedUnion('scope',[ownerSearchRequestSchema,publicSearchRequestSchema]);
export type SearchRequest=z.infer<typeof searchRequestSchema>;
export type SearchInput=z.input<typeof searchRequestSchema>;
export const publicSearchItemSchema=publicRecommendationSummarySchema;
export const ownerSearchItemSchema=publicSearchItemSchema.extend({accountId:contentIdSchema,category:contentCategorySchema,entityId:contentIdSchema,entity:entityCoreDtoSchema,publicationState:z.enum(['draft','published']),revision:z.number().int().positive().safe()}).strict().superRefine((v,ctx)=>{if(v.entityId!==v.entity.id||v.kind!==v.entity.kind)ctx.addIssue({code:'custom',message:'Inconsistent entity'});});
const base={version:z.literal('explorers-search/v1'),expiresAt:z.number().int().positive(),nextCursor:token.nullable()};
export const ownerSearchPageSchema=z.object({...base,scope:z.literal('owner'),snapshot:z.string().regex(/^(0|[1-9][0-9]{0,15})$/).refine(v=>Number.isSafeInteger(Number(v))),snapshotToken:token,items:z.array(ownerSearchItemSchema).max(100)}).strict();
export const publicSearchPageSchema=z.object({...base,scope:z.literal('public'),consistency:z.enum(['live','category-fenced']),items:z.array(publicSearchItemSchema).max(100)}).strict();
export const searchPageSchema=z.discriminatedUnion('scope',[ownerSearchPageSchema,publicSearchPageSchema]);
export const publicCollectionByIdSchema=z.object({id:contentIdSchema,category:contentCategorySchema,title:z.string().min(1).max(200),slug:z.string().max(200),description:z.string().max(5000).nullable(),heading:z.string().max(200).nullable()}).strict();
export const creatorProfileSchema=z.object({id:contentIdSchema,handle:z.string().max(30),displayName:z.string().max(200),accountType:z.string().max(100)}).strict();
export const ownerSearchErrorSchema=z.object({error:z.object({code:z.enum(['UNAUTHENTICATED','FORBIDDEN','NOT_FOUND','CONFLICT','RESOURCE_TOO_LARGE','INVALID_INPUT','UNAVAILABLE']),message:z.string(),requestId:z.string(),retryable:z.literal(true).optional()}).strict()}).strict();
export const publicSearchErrorSchema=z.object({version:z.literal('explorers-public-error/v1'),error:z.object({code:z.enum(['NOT_FOUND','PAGE_CHANGED','RESOURCE_TOO_LARGE','UNAVAILABLE','BAD_REQUEST']),retryable:z.literal(true).optional(),restart:z.literal(true).optional()}).strict()}).strict();
