import {z} from 'zod/v3';
const text=(n:number)=>z.string().trim().max(n).refine(v=>!/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(v)&&!/[\u0000-\u001f\u007f]/.test(v));
const id=z.number().int().positive().safe();const url=z.string().max(2048).url().refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port;});
const image=url.refine(v=>new URL(v).hostname==='image.tmdb.org');
export const movieGenreSchema=z.object({providerGenreId:id,name:text(200).refine(v=>v.length>0)}).strict();
const offer=z.object({providerId:id,name:text(200).refine(v=>v.length>0),logoUrl:image.nullable(),priority:z.number().int().nonnegative().safe()}).strict();
const region=z.object({link:url.nullable(),flatrate:z.array(offer).max(64),rent:z.array(offer).max(64),buy:z.array(offer).max(64)}).strict();
export const movieWatchSchema=z.record(z.string().regex(/^[A-Z]{2}$/),region).refine(v=>Object.keys(v).length<=32);
export const movieContextSchema=z.object({region:z.string().regex(/^[A-Z]{2}$/).default('US'),selectedProviderIds:z.array(id).max(8).refine(v=>new Set(v).size===v.length).nullable()}).strict();
export const movieDetailsSchema=z.object({mediaType:z.enum(['movie','tv']),originalTitle:text(1000).nullable(),yearText:text(100).nullable(),posterUrl:image.nullable(),backdropUrl:image.nullable(),genres:z.array(movieGenreSchema).max(32).refine(v=>new Set(v.map(x=>x.providerGenreId)).size===v.length),director:text(1000).nullable(),runtimeMinutes:z.number().int().nonnegative().max(2147483647).nullable(),providerRating:z.number().min(0).max(10).nullable(),overview:text(100000).nullable(),seasonCount:z.number().int().nonnegative().max(2147483647).nullable(),watchProviders:movieWatchSchema,cast:z.array(z.object({personId:id,creditId:text(200).refine(v=>v.length>0),name:text(1000).refine(v=>v.length>0),character:text(1000),profileUrl:image.nullable(),order:z.number().int().nonnegative().safe()}).strict()).max(200)}).strict().refine(v=>v.mediaType==='tv'||v.seasonCount===null);
export const movieSearchRequestSchema=z.object({query:text(200).refine(v=>v.length>0),mediaType:z.enum(['movie','tv']).optional(),limit:z.union([z.number().int(),z.string().regex(/^[1-9]\d?$/).transform(Number)]).pipe(z.number().min(1).max(24)).default(24),cursor:z.string().regex(/^[A-Za-z0-9_-]{32}$/).optional()}).strict();
export const movieCandidateSchema=z.object({provider:z.literal('tmdb'),externalKind:z.enum(['movie','tv']),externalId:z.string().regex(/^[1-9]\d{0,15}$/).refine(v=>Number.isSafeInteger(Number(v))),title:text(1000).refine(v=>v.length>0),posterUrl:image.nullable(),yearText:text(100).nullable()}).strict();
export const movieEntityDtoSchema=z.object({id:z.string().uuid(),kind:z.literal('movie'),title:text(500).refine(v=>v.length>0),origin:z.enum(['manual','provider']),details:movieDetailsSchema,provenance:z.object({provider:z.literal('tmdb'),externalKind:z.enum(['movie','tv']),externalId:movieCandidateSchema.shape.externalId,fetchedAt:z.number().int().nonnegative().safe(),sourceUrl:url,mappingVersion:z.literal(1)}).strict().nullable()}).strict().refine(v=>v.origin==='manual'?v.provenance===null:!!v.provenance&&v.provenance.externalKind===v.details.mediaType&&v.provenance.sourceUrl===`https://api.themoviedb.org/3/${v.details.mediaType}/${v.provenance.externalId}`);
export const resolveProviderMovieSchema=z.object({kind:z.literal('provider'),category:z.literal('movies'),provider:z.literal('tmdb'),externalKind:z.enum(['movie','tv']),externalId:movieCandidateSchema.shape.externalId}).strict();
export type MovieContext=z.infer<typeof movieContextSchema>;export type MovieDetails=z.infer<typeof movieDetailsSchema>;export type MovieCandidate=z.infer<typeof movieCandidateSchema>;


export const movieDisplayFieldsSchema=z.object({originalTitle:text(1000).nullable().optional(),yearText:text(100).nullable().optional(),director:text(1000).nullable().optional(),runtimeMinutes:z.number().int().nonnegative().max(2147483647).nullable().optional(),overview:text(100000).nullable().optional(),seasonCount:z.number().int().nonnegative().max(2147483647).nullable().optional()}).strict();
export const movieCandidatesSchema=z.object({version:z.literal('explorers-movie-candidates/v1'),items:z.array(movieCandidateSchema).max(24),nextCursor:z.string().regex(/^[A-Za-z0-9_-]{32}$/).nullable(),expiresAt:z.number().int().positive().safe()}).strict();

export const movieTermSchema=z.object({id:z.string().uuid(),category:z.literal('movies'),slug:text(100).refine(v=>v.length>0),label:text(200).refine(v=>v.length>0),position:z.number().int().min(0).max(31)}).strict();
export const movieTermsSchema=z.array(movieTermSchema).max(32).refine(v=>new Set(v.map(x=>x.id)).size===v.length&&v.every((x,i)=>x.position===i));
export const resolveManualMovieSchema=z.object({kind:z.literal('manual'),category:z.literal('movies'),details:movieDisplayFieldsSchema.extend({title:text(500).refine(v=>v.length>0),mediaType:z.enum(['movie','tv']).default('movie'),providerRating:z.number().min(0).max(10).nullable().optional()}).strict()}).strict().refine(v=>v.details.mediaType==='tv'||v.details.seasonCount==null);
export const emptyMovieDetails=(mediaType:'movie'|'tv'='movie'):MovieDetails=>({mediaType,originalTitle:null,yearText:null,posterUrl:null,backdropUrl:null,genres:[],director:null,runtimeMinutes:null,providerRating:null,overview:null,seasonCount:null,watchProviders:{},cast:[]});
