import {z} from 'zod/v3';
const text=(max:number)=>z.string().trim().max(max).refine(v=>!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v)&&!/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(v),'Invalid text');
export const bookTitleSchema=text(1000).refine(v=>v.length>0&&Array.from(v).length<=500&&!/[\u0000-\u001f\u007f]/.test(v),'Invalid title');
export const safeBookUrlSchema=z.string().max(2048).url().refine(v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&!u.port;}catch{return false;}},'Invalid URL');
const metadataUrl=safeBookUrlSchema.refine(v=>new URL(v).hostname==='books.google.com'&&new URL(v).protocol==='https:','Unapproved Book metadata URL');
const members=z.array(text(1000)).max(200);
const fields={subtitle:text(1000).nullable(),publisher:text(1000).nullable(),publishedDateText:text(100).nullable(),yearText:text(100).nullable(),description:text(100000).nullable(),coverUrl:metadataUrl.nullable(),coverLargeUrl:metadataUrl.nullable(),pageCount:z.number().int().nonnegative().max(2147483647).nullable(),isbn13:z.string().regex(/^\d{13}$/).nullable(),isbn10:z.string().regex(/^\d{9}[\dX]$/).nullable(),providerRating:z.number().min(0).max(5).nullable(),ratingsCount:z.number().int().nonnegative().max(2147483647).nullable(),languageTag:text(100).nullable(),previewLink:metadataUrl.nullable(),authors:members,subjects:members};
export const bookEntityDetailsSchema=z.object(fields).strict().refine(v=>new TextEncoder().encode(JSON.stringify(v)).length<=1024*1024,'Book details too large');
const {providerRating:_rating,ratingsCount:_count,...editable}=fields;
export const bookDisplayFieldsSchema=z.object(editable).partial().strict();
export const bookRecommendationContextSchema=z.object({buyLinks:z.array(z.object({name:text(200).refine(v=>v.length>0),url:safeBookUrlSchema,logo:safeBookUrlSchema.optional()}).strict()).max(20)}).strict();
const bookExternalIdSchema=z.string().regex(/^[A-Za-z0-9_-]{1,200}$/);
export const bookProvenanceSchema=z.object({provider:z.literal('google_books'),externalKind:z.literal('volume'),externalId:bookExternalIdSchema,fetchedAt:z.number().int().nonnegative().safe(),sourceUrl:z.string().max(2048).refine(v=>/^https:\/\/www\.googleapis\.com\/books\/v1\/volumes\/[A-Za-z0-9_-]+$/.test(v)),mappingVersion:z.literal(1)}).strict().refine(v=>v.sourceUrl===`https://www.googleapis.com/books/v1/volumes/${v.externalId}`,'Inconsistent Book provenance');
export const bookCandidateSchema=z.object({provider:z.literal('google_books'),externalKind:z.literal('volume'),externalId:bookExternalIdSchema,title:bookTitleSchema,preview:bookEntityDetailsSchema,provenance:bookProvenanceSchema,buyLinkSuggestion:safeBookUrlSchema.nullable()}).strict().refine(v=>v.externalId===v.provenance.externalId,'Inconsistent Book identity');
export const bookCandidatesSchema=z.object({version:z.literal('explorers-book-candidates/v1'),items:z.array(bookCandidateSchema).max(20),nextCursor:z.string().max(4096).nullable(),expiresAt:z.number().int().positive().safe()}).strict();
export const bookCandidateRequestSchema=z.object({query:z.string().trim().refine(v=>Array.from(v).length>=1&&Array.from(v).length<=200&&new TextEncoder().encode(v).length<=800&&!/[\u0000-\u001f\u007f]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(v)),limit:z.union([z.number().int(),z.string().regex(/^[1-9]\d?$/).transform(Number)]).pipe(z.number().min(1).max(20)).default(12),cursor:z.string().min(1).max(4096).optional()}).strict();
export const bookEntityDtoSchema=z.object({id:z.string().uuid(),kind:z.literal('book'),title:z.string().trim().refine(v=>v.length>0&&Array.from(v).length<=500),details:bookEntityDetailsSchema,provenance:bookProvenanceSchema.nullable(),origin:z.enum(['manual','provider'])}).strict();
export const resolveProviderBookSchema=z.object({kind:z.literal('provider'),category:z.literal('books'),provider:z.literal('google_books'),externalKind:z.literal('volume'),externalId:bookExternalIdSchema}).strict();
export const resolveManualBookSchema=z.object({kind:z.literal('manual'),category:z.literal('books'),details:z.object(editable).partial().extend({title:bookTitleSchema}).strict()}).strict();
export const replaceRecommendationEntitySchema=z.object({expectedRevision:z.number().int().positive().safe(),entityId:z.string().uuid()}).strict();
export type BookEntityDetails=z.infer<typeof bookEntityDetailsSchema>;
export type BookRecommendationContext=z.infer<typeof bookRecommendationContextSchema>;
export type BookCandidate=z.infer<typeof bookCandidateSchema>;
export type BookEntityDto=z.infer<typeof bookEntityDtoSchema>;
export const emptyBookDetails=():BookEntityDetails=>({subtitle:null,publisher:null,publishedDateText:null,yearText:null,description:null,coverUrl:null,coverLargeUrl:null,pageCount:null,isbn13:null,isbn10:null,providerRating:null,ratingsCount:null,languageTag:null,previewLink:null,authors:[],subjects:[]});
