export const EXPECTED_MUSIC_MIGRATION_ID = "0037_explorers_movies_provider_context" as const;
export const EXPECTED_MUSIC_MIGRATION_CHAIN = [
  "0001_runtime_baseline",
  "0002_identity_lifecycle",
  "0003_identity_lifecycle_hardening",
  "0004_identity_delete_saga",
  "0005_resource_bound_deletion_history",
  "0006_numeric_identity_lock",
  "0007_identity_provider_snapshot",
  "0008_credential_revocation_operations",
  "0009_credential_revocation_history_immutability",
  "0010_least_privilege_runtime_role",
  "0011_durable_publication_idempotency",
  "0012_publication_replay_expiry_guard",
  "0013_publication_operation_database_clock",
  "0014_durable_reactivation_authority",
  "0015_publication_operation_archive",
  "0016_publication_operation_retention",
  "0017_publication_idempotency_key_retirement",
  "0018_transactional_queue_replacement",
  "0019_queue_visibility_control",
  "0020_public_snapshot_revision",
  "0021_explorers_analytics_receipts",
  "0022_explorers_identity",
  "0023_explorers_authorization",
  "0024_explorers_profile_media",
  "0025_explorers_media_attachment_guard",
  "0026_explorers_media_slot_compatibility",
  "0027_explorers_lifecycle",
  "0028_explorers_recovery_proof_retention",
  "0029_explorers_recommendations",
  "0030_explorers_media_purpose_guard",
  "0031_explorers_content_revision",
  "0032_explorers_owner_page_indexes",
  "0033_explorers_recommendation_display_overrides",
  "0034_explorers_books_provider_context",
  "0035_explorers_book_cover_import",
  "0036_explorers_analytics_events",
  EXPECTED_MUSIC_MIGRATION_ID,
] as const;
export const LEGACY_CONTAINMENT_MIGRATION_MARKER = "containment-no-schema-change" as const;

export const DEPLOYABLE_MUSIC_MIGRATION_MARKERS = [
  LEGACY_CONTAINMENT_MIGRATION_MARKER,
  "0002_identity_lifecycle",
  "0003_identity_lifecycle_hardening",
  "0004_identity_delete_saga",
  "0005_resource_bound_deletion_history",
  "0006_numeric_identity_lock",
  "0007_identity_provider_snapshot",
  "0008_credential_revocation_operations",
  "0009_credential_revocation_history_immutability",
  "0010_least_privilege_runtime_role",
  "0011_durable_publication_idempotency",
  "0012_publication_replay_expiry_guard",
  "0013_publication_operation_database_clock",
  "0014_durable_reactivation_authority",
  "0015_publication_operation_archive",
  "0016_publication_operation_retention",
  "0017_publication_idempotency_key_retirement",
  "0018_transactional_queue_replacement",
  "0019_queue_visibility_control",
  "0020_public_snapshot_revision",
  "0021_explorers_analytics_receipts",
  "0022_explorers_identity",
  "0023_explorers_authorization",
  "0024_explorers_profile_media",
  "0025_explorers_media_attachment_guard",
  "0026_explorers_media_slot_compatibility",
  "0027_explorers_lifecycle",
  "0028_explorers_recovery_proof_retention",
  "0029_explorers_recommendations",
  "0030_explorers_media_purpose_guard",
  "0031_explorers_content_revision",
  "0032_explorers_owner_page_indexes",
  "0033_explorers_recommendation_display_overrides",
  "0034_explorers_books_provider_context",
  "0035_explorers_book_cover_import",
  "0036_explorers_analytics_events",
  EXPECTED_MUSIC_MIGRATION_ID,
] as const;

export type DeployableMusicMigrationMarker = typeof DEPLOYABLE_MUSIC_MIGRATION_MARKERS[number];

export function musicMigrationMarkerRank(marker: string): number | undefined {
  const rank = DEPLOYABLE_MUSIC_MIGRATION_MARKERS.indexOf(marker as DeployableMusicMigrationMarker);
  return rank < 0 ? undefined : rank;
}
