import { describe, expect, it } from 'vitest';
import { runReleaseCli, readManifestFile } from '../../../../scripts/platform-release';
import { mkdtemp, writeFile, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { resolveExplorersAuthConfig } from '../../auth/betterAuth';
import { resolveObjectStorage } from '../../services/objectStorage';
import { resolveMusicDatabaseConnection } from '../../config/music-database-config';
import { SCHEMA_FLOOR, canonicalDigest, parseRelease, parseReadiness, validateEnvironmentPair, runtimeMapping, verifyRelease, parseStrictJson } from '../../../../scripts/platform-release-contract';

const sha = 'a'.repeat(40), digest = 'sha256:' + 'b'.repeat(64);
function release() {
  const value: any = { version: 1, sourceCommit: sha, schemaVersion: SCHEMA_FLOOR, producerRunId: '123', producerRepository: 'tandavkrishna27/explorers.earth', producerWorkflow: '.github/workflows/platform-candidate.yml', testEvidenceRef: 'artifact:123/qualification', images: { api: { repository: 'ghcr.io/tandavkrishna27/explorers-api', digest, platforms: { 'linux/amd64': { digest, smokeEvidenceRef: 'artifact:123/api-smoke' } } }, web: { repository: 'ghcr.io/tandavkrishna27/explorers-web', digest, platforms: { 'linux/amd64': { digest, smokeEvidenceRef: 'artifact:123/web-smoke' } } } } };
  value.manifestDigest = canonicalDigest(value); return value;
}
function readiness(environment: 'qa' | 'production' = 'qa') {
  const prefix = environment === 'qa' ? 'qa' : 'prod';
  return { version: 1, environment, hostAlias: prefix + '-host', sshUser: 'deploy', sshPort: 22, knownHostKeyRef: prefix + '_KNOWN_HOST', architecture: 'linux/amd64', dockerVersion: '29.2.1', composeVersion: '2.39.0', publicOrigin: `https://${prefix}.example.test`, internalPorts: { api: 5000, web: 80, postgres: 5432 }, database: { name: prefix + '_db', volume: prefix + '_data', runtimeRole: prefix + '_app', migratorRole: prefix + '_migrator', runtimePasswordRef: prefix + '_DB_PASSWORD_FILE', migratorPasswordRef: prefix + '_MIGRATOR_PASSWORD_FILE' }, storage: { bucket: 'shared-private-bucket', region: 'ap-south-1', prefix: prefix + '/', boundary: 'application-shared-principal' }, google: { clientIdRef: 'GOOGLE_CLIENT_ID', clientSecretRef: 'GOOGLE_CLIENT_SECRET', callback: `https://${prefix}.example.test/api/auth/callback/google` }, appSecretRef: prefix + '_APP_SECRET', publicConfig: { origin: `https://${prefix}.example.test`, apiPath: '/api', socketPath: '/socket.io' } };
}
describe('offline platform release contracts', () => {
  it.each([35, 36])('rejects historical schema floor %s even with a coherent detached digest', schemaVersion => {
    const value = release(); value.schemaVersion = schemaVersion; value.manifestDigest = canonicalDigest(value);
    expect(() => parseRelease(value)).toThrow('RELEASE_SCHEMA_INVALID');
  });
  it('accepts complete structural manifests without granting authority', () => { expect(parseRelease(release()).schemaVersion).toBe(SCHEMA_FLOOR); expect(() => verifyRelease(release(), readiness())).toThrow('TRUSTED_AUTHORITY_UNAVAILABLE'); });
  it('canonicalizes ordering and excludes only detached digest', () => { expect(canonicalDigest({ z: 'é', a: { b: 1 } })).toBe(canonicalDigest({ a: { b: 1 }, z: 'é', manifestDigest: 'ignored' })); expect(canonicalDigest({ a: { b: 2 } })).not.toBe(canonicalDigest({ a: { b: 1 } })); });
  it.each([NaN, Infinity, undefined])('rejects non JSON canonical value %s', value => expect(() => canonicalDigest({ value })).toThrow());
  it('rejects duplicate JSON keys even escaped aliases', () => { expect(() => parseStrictJson('{"a":1,"\\u0061":2}')).toThrow('DUPLICATE_JSON_KEY'); expect(parseStrictJson('{"a":{"a":1}}')).toEqual({ a: { a: 1 } }); });
  it.each(['sourceCommit','schemaVersion','manifestDigest','producerRunId','producerWorkflow','producerRepository','images','testEvidenceRef'])('rejects malformed release %s', key => { const v = release(); v[key] = null; expect(() => parseRelease(v)).toThrow(); });
  it('rejects tampering and caller trust assertions', () => { const v = release(); v.sourceCommit = 'c'.repeat(40); expect(() => parseRelease(v)).toThrow('MANIFEST_DIGEST_MISMATCH'); expect(() => parseRelease({ ...release(), trusted: true })).toThrow('RELEASE_SCHEMA_INVALID'); });
  it('rejects unsupported schema and foreign image repository', () => { const v = release(); v.schemaVersion = SCHEMA_FLOOR - 1; v.manifestDigest = canonicalDigest(v); expect(() => parseRelease(v)).toThrow(); v.schemaVersion = SCHEMA_FLOOR; v.images.api.repository = 'ghcr.io/attacker/api'; v.manifestDigest = canonicalDigest(v); expect(() => parseRelease(v)).toThrow(); });
  it('rejects mutable tags and missing architecture evidence', () => { const v = release(); v.images.api.digest = 'latest'; expect(() => parseRelease(v)).toThrow(); const w = release(); w.images.web.platforms = {}; w.manifestDigest = canonicalDigest(w); expect(() => parseRelease(w)).toThrow(); });
  it('rejects raw caller authority irrespective of successful claims', () => expect(() => verifyRelease(release(), readiness(), { success: true, trusted: true } as never)).toThrow('TRUSTED_AUTHORITY_UNAVAILABLE'));
  it('validates separate environments with shared bucket and Google references', () => expect(() => validateEnvironmentPair(readiness(), readiness('production'))).not.toThrow());
  it('rejects missing QA hostname with named error', () => expect(() => parseReadiness({ ...readiness(), publicOrigin: '' })).toThrow('QA_HOSTNAME_MISSING'));
  it.each(['http://qa.example.test','https://user:password@qa.example.test','https://qa.example.test/path','https://qa.example.test/'])('rejects unsafe origin %s', publicOrigin => expect(() => parseReadiness({ ...readiness(), publicOrigin })).toThrow());
  it('rejects callback mismatch and server credentials in public configuration', () => { const v = readiness(); v.google.callback += '/wrong'; expect(() => parseReadiness(v)).toThrow(); expect(() => parseReadiness({ ...readiness(), publicConfig: { ...readiness().publicConfig, GOOGLE_CLIENT_SECRET: 'sentinel' } })).toThrow(); });
  it.each(['prod/','qa/../prod/','qa%2f','/qa/'])('rejects QA namespace %s', prefix => { const v = readiness(); v.storage.prefix = prefix; expect(() => parseReadiness(v)).toThrow(); });
  it('rejects shared operational isolation references', () => { const qa = readiness(), prod = readiness('production'); prod.database.runtimePasswordRef = qa.database.runtimePasswordRef; expect(() => validateEnvironmentPair(qa, prod)).toThrow(); prod.database.runtimePasswordRef = 'prod_DB_PASSWORD_FILE'; prod.hostAlias = qa.hostAlias; expect(() => validateEnvironmentPair(qa, prod)).toThrow(); });
  it('rejects role equality, aliases and unknown config', () => { const v = readiness(); v.database.runtimeRole = v.database.migratorRole; expect(() => parseReadiness(v)).toThrow(); expect(() => parseReadiness({ ...readiness(), DATABASE_URL: 'sentinel' })).toThrow(); });
  it('maps only implemented runtime names and protected references', () => { const result = runtimeMapping(readiness()); expect(result.values).toMatchObject({ NODE_ENV: 'production', EXPLORERS_DEPLOYMENT_TIER: 'qa', EXPLORERS_MEDIA_ENVIRONMENT: 'qa', EXPLORERS_PUBLIC_ORIGIN: 'https://qa.example.test', MUSIC_DATABASE_HOST: 'postgres' }); expect(result.secretRefs.EXPLORERS_AUTH_SECRET).toBe('qa_APP_SECRET'); expect(result.secretRefs.MUSIC_DATABASE_PASSWORD_FILE).toBe('qa_DB_PASSWORD_FILE'); expect(result.values).not.toHaveProperty('DATABASE_URL'); expect(result.values).not.toHaveProperty('BETTER_AUTH_URL'); });
  it('CLI inspection does not assert qualified success', async () => { const output = await runReleaseCli(['inspect','--manifest','fixture.json'], async () => JSON.stringify(release())); expect(output).toEqual({ exitCode: 0, stdout: 'STRUCTURALLY_VALID_UNQUALIFIED\n', stderr: '' }); });
  it('CLI verify refuses fabricated trusted proof and never echoes secrets', async () => { const output = await runReleaseCli(['verify','--manifest','sentinel-secret.json','--readiness','ready.json','--environment','qa'], async path => JSON.stringify(path === 'ready.json' ? readiness() : release())); expect(output.exitCode).toBe(1); expect(output.stderr).toBe('TRUSTED_AUTHORITY_UNAVAILABLE\n'); expect(output.stdout).toBe(''); });
  it.each([[], ['deploy'], ['verify','--manifest','x'], ['inspect','--manifest','x','--manifest','y'], ['inspect','--manifest','x','--trusted','true']].map(args => [args]))('CLI rejects unsupported or incomplete flags %j', async args => expect((await runReleaseCli(args, async () => '{}')).stderr).toBe('CLI_ARGUMENTS_INVALID\n'));
  it('CLI rejects wrong environment and excessive/invalid input safely', async () => { const args = ['verify','--manifest','m','--readiness','r','--environment','production']; expect((await runReleaseCli(args, async p => JSON.stringify(p === 'r' ? readiness() : release()))).stderr).toBe('ENVIRONMENT_MISMATCH\n'); expect((await runReleaseCli(['inspect','--manifest','m'], async () => 'SENTINEL-SECRET')).stderr).toBe('JSON_INVALID\n'); expect((await runReleaseCli(['inspect','--manifest','m'], async () => ' '.repeat(65537))).stderr).toBe('JSON_SIZE_LIMIT\n'); });
  it('rejects missing selected architecture even for structurally valid release', () => { const r = readiness(); r.architecture = 'linux/arm64'; expect(() => verifyRelease(release(),r)).toThrow('ARCHITECTURE_EVIDENCE_MISSING'); });
  it('rejects forged evidence run and unsupported platform', () => { const m = release(); m.testEvidenceRef = 'artifact:999/qualification'; m.manifestDigest = canonicalDigest(m); expect(() => parseRelease(m)).toThrow('EVIDENCE_RUN_MISMATCH'); const n = release(); n.images.api.platforms = { 'windows/amd64': n.images.api.platforms['linux/amd64'] }; n.manifestDigest = canonicalDigest(n); expect(() => parseRelease(n)).toThrow('RELEASE_SCHEMA_INVALID'); });
  it('retains nested digest fields in canonical identity', () => expect(canonicalDigest({ a: { manifestDigest: 'one' } })).not.toBe(canonicalDigest({ a: { manifestDigest: 'two' } })));
  it('rejects oversized depth, infinity syntax and malformed JSON safely', () => { expect(() => parseStrictJson('['.repeat(34)+'0'+']'.repeat(34))).toThrow('JSON_DEPTH_LIMIT'); expect(() => parseStrictJson('{"a":1e999}')).toThrow('NON_JSON_VALUE'); expect(() => parseStrictJson('{"a":1,}')).toThrow('JSON_INVALID'); });
  it('templates remain intentionally non deployable', async () => { for (const name of ['qa','production']) { const r = parseStrictJson(await readFile(resolve(process.cwd(), '../deploy/environments/'+name+'.example.json'),'utf8')); expect(() => parseReadiness(r)).toThrow(name === 'qa' ? 'QA_HOSTNAME_MISSING' : 'READINESS_SCHEMA_INVALID'); } });
  it('reads bounded regular files and sanitizes filesystem errors', async () => { const dir = await mkdtemp(join(tmpdir(),'platform-contract-')); try { const file = join(dir,'manifest.json'); await writeFile(file, JSON.stringify(release())); expect((await runReleaseCli(['inspect','--manifest',file])).exitCode).toBe(0); await writeFile(file,' '.repeat(65537)); await expect(readManifestFile(file)).rejects.toThrow('MANIFEST_FILE_INVALID'); expect((await runReleaseCli(['inspect','--manifest',dir])).stderr).toBe('MANIFEST_FILE_INVALID\n'); expect((await runReleaseCli(['inspect','--manifest',join(dir,'sentinel-secret-missing')])).stderr).toBe('MANIFEST_READ_FAILED\n'); } finally { await rm(dir,{recursive:true,force:true}); } });
  it('mapped names are actually accepted by auth, storage and protected DB resolvers', async () => { const mapping = runtimeMapping(readiness()); const env = { ...mapping.values, EXPLORERS_AUTH_SECRET: 'x'.repeat(32), GOOGLE_CLIENT_ID: 'dummy-client', GOOGLE_CLIENT_SECRET: 'dummy-secret', MUSIC_DATABASE_PASSWORD_FILE: '/synthetic/protected-reference' }; expect(resolveExplorersAuthConfig(env).googleCallbackURL).toBe(readiness().google.callback); expect(resolveObjectStorage(env).environment).toBe('qa'); const db = await resolveMusicDatabaseConnection(env,'runtime',{readSecretFile: async () => Buffer.alloc(32,7).toString('base64url')}); expect(db.user).toBe('qa_app'); expect(db.host).toBe('postgres'); });
  it('rejects public reference pointing at application secret', () => { const r = readiness() as any; r.publicConfig.mapsBrowserKeyRef = r.appSecretRef; expect(() => parseReadiness(r)).toThrow('PUBLIC_SECRET_REFERENCE'); });
});
