import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {discoverOwnedShard, linuxProcessGroupOwner} from './browser-shard-executor.mjs';
import {attestSourceTree} from './browser-source-attestation.mjs';
import {planShards} from './browser-shard-plan.mjs';
const hash = bytes=>createHash('sha256').update(bytes).digest('hex');
const identity={file:'explorers-earth/e2e/a.spec.ts',titlePath:['case'],project:'',repeat:0};
const report=()=>({errors:[],suites:[{title:'a.spec.ts',specs:[{file:'a.spec.ts',title:'case',ok:true,tests:[{projectName:'',expectedStatus:'passed',annotations:[],results:[],status:'skipped'}]}]}]});
async function fixture(t){
 const root=await fs.mkdtemp(join(tmpdir(),'owned-shard-contract-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const sourceRoot=join(root,'source'),allocationRoot=join(root,'runs');await fs.mkdir(sourceRoot);await fs.mkdir(allocationRoot);
 const contents={'explorers-earth/e2e/a.spec.ts':'test source\n','explorers-earth/playwright.music-publishing.config.ts':'config\n','explorers-earth/package-lock.json':'{}\n','tunes/package-lock.json':'{}\n'};
 const files=[];for(const [path,content] of Object.entries(contents)){await fs.mkdir(join(sourceRoot,path,'..'),{recursive:true});await fs.writeFile(join(sourceRoot,path),content);files.push({path,mode:'100644',policy:'lf',committed:Buffer.from(content)});}
 const source={root:sourceRoot,sha:'a'.repeat(40),files,trackedPaths:files.map(f=>f.path),configPaths:['explorers-earth/playwright.music-publishing.config.ts'],lockPaths:['explorers-earth/package-lock.json','tunes/package-lock.json'],directoryScopes:['explorers-earth/e2e'],fileScopes:Object.keys(contents).filter(p=>!p.includes('/e2e/'))};
 const a=attestSourceTree({...source,untracked:[],files:files.map(f=>({...f,observed:f.committed,observedKind:'file'}))});
 const plan=planShards({identities:[identity],provenance:a.provenance,shardCount:1});
 const producer={repository:'o/r',workflow:'browser',runId:'1',attempt:1,event:'pull_request',ref:'refs/pull/1/merge',shardJobs:{1:'job'}};
 const nodePath=join(root,'node');await fs.writeFile(nodePath,'fake node');
 const frontend=join(root,'frontend-deps'),tunes=join(root,'tunes-deps');for(const p of [frontend,tunes]){await fs.mkdir(p);await fs.writeFile(join(p,'.package-lock.json'),'installed');}
 await fs.mkdir(join(frontend,'@playwright/test'),{recursive:true});await fs.writeFile(join(frontend,'@playwright/test/cli.js'),'cli');await fs.writeFile(join(frontend,'@playwright/test/package.json'),JSON.stringify({version:'1.61.1'}));
 const authority={allocationRoot,source,plan,producer,lane:'publishing',projects:{'':1},runtime:{nodePath,nodeHash:hash('fake node'),nodeVersion:'24.21.0',playwrightVersion:'1.61.1'},dependencies:{frontend:{root:frontend,installationHash:hash('installed')},tunes:{root:tunes,installationHash:hash('installed')},cliHash:hash('cli')}};
 let cleanup=0,calls=[];
 const owner={kind:'synthetic-test-only',async run(command,args,options){calls.push({command,args,options});return{status:0,signal:null,stdout:JSON.stringify(report()),stderr:''};},async cleanup(){cleanup++;return{proved:true};}};
 return{authority,owner,calls,get cleanup(){return cleanup;},root};
}
const request={mode:'discover',shard:1};
test('owned discovery records exact evidence, never a qualifying runtime receipt',async t=>{const f=await fixture(t);const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,true);assert.equal(r.kind,'discovery-only');assert.equal(r.runtimeQualified,false);assert.equal(f.cleanup,1);assert.equal(f.calls.length,1);assert.ok(f.calls[0].args.includes('--list'));assert.ok(f.calls[0].args.includes('--test-list'));assert.equal(f.calls[0].options.shell,false);assert.equal(f.calls[0].options.env.CI,'true');assert.equal((await fs.stat(r.artifactRoot)).isDirectory(),true);await assert.rejects(fs.stat(r.workspace));const ledger=JSON.parse(await fs.readFile(r.receiptPath,'utf8'));assert.equal(ledger.runtimeQualified,false);assert.equal(ledger.producer.shardJobs[1],'job');});
for(const [name,edit] of [['wrong source',f=>fs.writeFile(join(f.authority.source.root,'explorers-earth/e2e/a.spec.ts'),'dirty')],['untracked source',f=>fs.writeFile(join(f.authority.source.root,'explorers-earth/e2e/extra.ts'),'extra')],['node mismatch',async f=>{f.authority.runtime.nodeHash='0'.repeat(64);}],['install mismatch',async f=>{f.authority.dependencies.frontend.installationHash='0'.repeat(64);}],['producer mapping',async f=>{f.authority.producer.shardJobs={};}],['unknown shard',async f=>{}]]) test(`executor rejects ${name} with a failure record`,async t=>{const f=await fixture(t);await edit(f);const r=await discoverOwnedShard(name==='unknown shard'?{...request,shard:2}:request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(f.calls.length,0);assert.equal(JSON.parse(await fs.readFile(r.receiptPath,'utf8')).passed,false);});
for(const key of ['PLAYWRIGHT_EXTERNAL_BASE_URL','DATABASE_URL','NODE_OPTIONS','NODE_PATH','DOCKER_HOST'])test(`ambient ${key} cannot become authority`,async t=>{const f=await fixture(t);const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{[key]:'secret'}});assert.equal(r.passed,false);assert.equal(f.calls.length,0);assert.doesNotMatch(await fs.readFile(r.receiptPath,'utf8'),/secret/);});
test('untrusted request cannot supply command, path or producer',async t=>{const f=await fixture(t);const r=await discoverOwnedShard({...request,args:['--grep','.*'],producer:'fake',output:'../escape'},f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(f.calls.length,0);});
for(const [name,child] of [['exit',{status:1,signal:null,stdout:'{}',stderr:'secret token'}],['signal',{status:null,signal:'SIGTERM',stdout:'',stderr:''}],['malformed',{status:0,signal:null,stdout:'bad',stderr:''}],['extra selection',{status:0,signal:null,stdout:JSON.stringify({...report(),suites:[]}),stderr:''}]])test(`child ${name} cannot leave a passing receipt`,async t=>{const f=await fixture(t);f.owner.run=async()=>child;const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(f.cleanup,1);assert.equal(JSON.parse(await fs.readFile(r.receiptPath,'utf8')).passed,false);assert.doesNotMatch(await fs.readFile(r.receiptPath,'utf8'),/secret token/);});
test('failed tree cleanup retains red evidence and workspace rather than claiming clean',async t=>{const f=await fixture(t);f.owner.cleanup=async()=>({proved:false});const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(r.cleanup,'failed');assert.equal((await fs.stat(r.workspace)).isDirectory(),true);});
test('cancellation invokes owned cleanup and leaves red record',async t=>{const f=await fixture(t),controller=new AbortController();f.owner.run=async()=>{controller.abort();return{status:0,signal:null,stdout:JSON.stringify(report()),stderr:''};};const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{},signal:controller.signal});assert.equal(r.passed,false);assert.equal(f.cleanup,1);});
test('source symlink is rejected before copy/child',async t=>{const f=await fixture(t);const p=join(f.authority.source.root,'explorers-earth/e2e/link');await fs.symlink(join(f.authority.source.root,'tunes'),p,'junction');const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(f.calls.length,0);});
test('allocation root symlink cannot redirect output authority',async t=>{const f=await fixture(t);const link=join(f.root,'redirect');await fs.symlink(f.authority.allocationRoot,link,'junction');f.authority.allocationRoot=link;await assert.rejects(()=>discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}}));});
test('real Windows launch fails closed without native descendant owner',async t=>{const f=await fixture(t);const r=await discoverOwnedShard(request,f.authority,{platform:'win32',ambient:{}});assert.equal(r.passed,false);assert.equal(r.reason,'WINDOWS_OWNER_UNAVAILABLE');});
test('runtime mode stays blocked in this discovery-only ticket',async t=>{const f=await fixture(t);const r=await discoverOwnedShard({...request,mode:'execute'},f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(f.calls.length,0);});
import {EventEmitter} from 'node:events';
function fakeLinuxProcess(){const child=new EventEmitter();child.pid=4321;child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>{};return child;}
test('Linux owner uses a distinct process group and proves it absent before clean',async()=>{const child=fakeLinuxProcess();let options,alive=true;const signals=[];const owner=linuxProcessGroupOwner({spawnProcess(_command,_args,o){options=o;queueMicrotask(()=>child.emit('close',0,null));return child;},kill(pid,signal){assert.equal(pid,-4321);if(signal===0){if(!alive)throw Object.assign(new Error('gone'),{code:'ESRCH'});return;}signals.push(signal);if(signal==='SIGKILL')alive=false;},pause:async()=>{}});const result=await owner.run('/node',['cli','--list'],{cwd:'/owned',env:{CI:'true'},timeoutMs:1000,maxOutputBytes:1024});assert.equal(result.status,0);assert.equal(options.detached,true);assert.equal(options.shell,false);assert.deepEqual(await owner.cleanup(),{proved:true});assert.deepEqual(signals,['SIGTERM','SIGKILL']);});
test('Linux owner cannot call permission-denied or still-live group clean',async()=>{const child=fakeLinuxProcess();const owner=linuxProcessGroupOwner({spawnProcess(){queueMicrotask(()=>child.emit('close',0,null));return child;},kill(_pid,signal){if(signal==='SIGTERM')throw Object.assign(new Error('denied'),{code:'EPERM'});},pause:async()=>{}});await owner.run('/node',[],{cwd:'/owned',env:{},timeoutMs:1000,maxOutputBytes:1024});assert.deepEqual(await owner.cleanup(),{proved:false});});
test('owned filesystem remains isolated across concurrent synthetic shards',async t=>{const f=await fixture(t);const [a,b]=await Promise.all([discoverOwnedShard(request,f.authority,{owner:{...f.owner},ambient:{}}),discoverOwnedShard(request,f.authority,{owner:{...f.owner},ambient:{}})]);assert.equal(a.passed,true);assert.equal(b.passed,true);assert.notEqual(a.root,b.root);assert.notEqual(a.artifactRoot,b.artifactRoot);const one=await fs.readFile(a.receiptPath,'utf8');const two=await fs.readFile(b.receiptPath,'utf8');assert.match(one,/discovery-only/);assert.match(two,/discovery-only/);});
test('unexpected workspace link blocks recursive cleanup rather than following it',async t=>{const f=await fixture(t);f.owner.run=async(_cmd,_args,o)=>{await fs.symlink(f.authority.source.root,join(o.cwd,'unexpected-link'),'junction');return{status:0,signal:null,stdout:JSON.stringify(report()),stderr:''};};const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(r.cleanup,'failed');assert.equal(await fs.readFile(join(f.authority.source.root,'explorers-earth/e2e/a.spec.ts'),'utf8'),'test source\n');});
test('missing child errors and thrown cleanup still retain a red record',async t=>{const f=await fixture(t);f.owner.run=async()=>{throw new Error('spawn secret');};f.owner.cleanup=async()=>{throw new Error('cleanup secret');};const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);assert.equal(r.cleanup,'failed');assert.doesNotMatch(await fs.readFile(r.receiptPath,'utf8'),/spawn secret|cleanup secret/);});
test('child source mutation invalidates source-bound discovery before green',async t=>{const f=await fixture(t);f.owner.run=async(_cmd,_args,o)=>{await fs.writeFile(join(o.cwd,'e2e/a.spec.ts'),'changed');return{status:0,signal:null,stdout:JSON.stringify(report()),stderr:''};};const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}});assert.equal(r.passed,false);});
test('native Linux owner cannot be mislabeled as Windows ownership',async t=>{const f=await fixture(t);f.owner.kind='native-linux-process-group';const r=await discoverOwnedShard(request,f.authority,{owner:f.owner,platform:'win32',ambient:{}});assert.equal(r.passed,false);assert.equal(f.calls.length,0);});
test('Linux timeout resolves even when child never emits close and group is denied',async()=>{const child=fakeLinuxProcess();const owner=linuxProcessGroupOwner({spawnProcess(){return child;},kill(){throw Object.assign(new Error('denied'),{code:'EPERM'});},pause:async()=>{}});const result=await Promise.race([owner.run('/node',[],{cwd:'/owned',env:{},timeoutMs:5,maxOutputBytes:16}),new Promise(resolve=>setTimeout(()=>resolve({hung:true}),100))]);assert.equal(result.hung,undefined);assert.equal(result.error.code,'CHILD_TIMEOUT');assert.deepEqual(await owner.cleanup(),{proved:false});});
test('Linux output limit retains bounded bytes and resolves without child close',async()=>{const child=fakeLinuxProcess();const owner=linuxProcessGroupOwner({spawnProcess(){queueMicrotask(()=>child.stdout.emit('data',Buffer.alloc(1000,65)));return child;},kill(){throw Object.assign(new Error('gone'),{code:'ESRCH'});},pause:async()=>{}});const result=await Promise.race([owner.run('/node',[],{cwd:'/owned',env:{},timeoutMs:1000,maxOutputBytes:16}),new Promise(resolve=>setTimeout(()=>resolve({hung:true}),100))]);assert.equal(result.hung,undefined);assert.equal(result.error.code,'CHILD_OUTPUT_LIMIT');assert.ok(Buffer.byteLength(result.stdout)+Buffer.byteLength(result.stderr)<=16);});
test('Linux owner preserves Unicode split across pipe chunks',async()=>{const child=fakeLinuxProcess();const bytes=Buffer.from('é🌍');const owner=linuxProcessGroupOwner({spawnProcess(){queueMicrotask(()=>{child.stdout.emit('data',bytes.subarray(0,1));child.stdout.emit('data',bytes.subarray(1,4));child.stdout.emit('data',bytes.subarray(4));child.emit('close',0,null);});return child;},kill(){throw Object.assign(new Error('gone'),{code:'ESRCH'});}});const result=await owner.run('/node',[],{cwd:'/owned',env:{},timeoutMs:1000,maxOutputBytes:16});assert.equal(result.stdout,'é🌍');assert.equal(result.status,0);});
test('Linux abort resolves without close and requires group cleanup proof',async()=>{const child=fakeLinuxProcess(),controller=new AbortController();const owner=linuxProcessGroupOwner({spawnProcess(){queueMicrotask(()=>controller.abort());return child;},kill(){throw Object.assign(new Error('gone'),{code:'ESRCH'});}});const result=await owner.run('/node',[],{cwd:'/owned',env:{},signal:controller.signal,timeoutMs:1000,maxOutputBytes:16});assert.equal(result.error.code,'CHILD_CANCELLED');assert.deepEqual(await owner.cleanup(),{proved:true});});
test('Linux spawn error cannot masquerade as successful exit',async()=>{const child=fakeLinuxProcess();child.pid=undefined;const owner=linuxProcessGroupOwner({spawnProcess(){queueMicrotask(()=>child.emit('error',Object.assign(new Error('missing'),{code:'ENOENT'})));return child;}});const result=await owner.run('/node',[],{cwd:'/owned',env:{},timeoutMs:1000,maxOutputBytes:16});assert.equal(result.status,null);assert.equal(result.error.code,'ENOENT');assert.deepEqual(await owner.cleanup(),{proved:true});});
test('replaced output directory cannot redirect a receipt outside owned root',async t=>{const f=await fixture(t);let outside;f.owner.run=async(_cmd,args)=>{const output=args.find(a=>a.startsWith('--output=')).slice('--output='.length);const artifacts=join(output,'..');outside=join(f.root,'outside');await fs.mkdir(outside);await fs.rm(artifacts,{recursive:true});await fs.symlink(outside,artifacts,'junction');return{status:0,signal:null,stdout:JSON.stringify(report()),stderr:''};};await assert.rejects(()=>discoverOwnedShard(request,f.authority,{owner:f.owner,ambient:{}}));assert.deepEqual(await fs.readdir(outside),[]);});
