import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {resolveNodeOwnedNpm,probeNodeOwnedNpm} from './replatform-e2e.mjs';
function fixture(platform){const directory=mkdtempSync(join(tmpdir(),'node-owned-npm-contract-'));const node=platform==='linux'?join(directory,'bin/node'):join(directory,'node.exe');const pkg=platform==='linux'?join(directory,'lib/node_modules/npm'):join(directory,'node_modules/npm');mkdirSync(dirname(node),{recursive:true});mkdirSync(join(pkg,'bin'),{recursive:true});writeFileSync(node,'controlled executable');writeFileSync(join(pkg,'package.json'),JSON.stringify({name:'npm',version:'11.19.0',bin:{npm:'bin/npm-cli.js'}}));writeFileSync(join(pkg,'bin/npm-cli.js'),'controlled CLI');return {directory,node,pkg,cleanup(){rmSync(directory,{recursive:true,force:true});}};}
for(const platform of ['win32','linux'])test(`${platform} distribution resolves only Node-owned npm`,()=>{const f=fixture(platform);try{const result=resolveNodeOwnedNpm(f.node,{platform});assert.equal(result.nodeExecutable,realpathSync(f.node));assert.equal(result.npmCli,realpathSync(join(f.pkg,'bin/npm-cli.js')));assert.equal(result.packageVersion,'11.19.0');const calls=[];const probe=probeNodeOwnedNpm(f.node,{platform,expectedNodeVersion:'24.21.0',run:(exe,args)=>{calls.push({exe,args});return args[0]==='--version'?'v24.21.0\n':'11.19.0\n';}});assert.equal(probe.npmVersion,'11.19.0');assert.deepEqual(calls,[{exe:realpathSync(f.node),args:['--version']},{exe:realpathSync(f.node),args:[realpathSync(join(f.pkg,'bin/npm-cli.js')),'--version']}]);}finally{f.cleanup();}});
for(const [name,mutate] of [['missing CLI',f=>rmSync(join(f.pkg,'bin/npm-cli.js'))],['missing package',f=>rmSync(join(f.pkg,'package.json'))],['foreign package identity',f=>writeFileSync(join(f.pkg,'package.json'),JSON.stringify({name:'foreign',version:'11.19.0',bin:{npm:'bin/npm-cli.js'}}))],['invalid bin metadata',f=>writeFileSync(join(f.pkg,'package.json'),JSON.stringify({name:'npm',version:'11.19.0',bin:{npm:'../../foreign.js'}}))],['ambiguous adjacency',f=>{const other=join(f.directory,'bin/node_modules/npm/bin');mkdirSync(other,{recursive:true});writeFileSync(join(other,'npm-cli.js'),'foreign');}]])test(`resolver rejects ${name}`,()=>{const f=fixture('linux');try{mutate(f);assert.throws(()=>resolveNodeOwnedNpm(f.node,{platform:'linux'}));}finally{f.cleanup();}});
test('resolved Node symlink determines its actual owning prefix',()=>{const f=fixture('linux');try{const alias=join(f.directory,'alias-bin');symlinkSync(dirname(f.node),alias,'junction');assert.equal(resolveNodeOwnedNpm(join(alias,'node'),{platform:'linux'}).nodeExecutable,realpathSync(f.node));}finally{f.cleanup();}});
test('npm package symlink escape is rejected',()=>{const f=fixture('linux'),foreign=mkdtempSync(join(tmpdir(),'foreign-npm-contract-'));try{rmSync(f.pkg,{recursive:true});mkdirSync(join(foreign,'bin'));writeFileSync(join(foreign,'package.json'),JSON.stringify({name:'npm',version:'11.19.0',bin:{npm:'bin/npm-cli.js'}}));writeFileSync(join(foreign,'bin/npm-cli.js'),'foreign');symlinkSync(foreign,f.pkg,'junction');assert.throws(()=>resolveNodeOwnedNpm(f.node,{platform:'linux'}));}finally{f.cleanup();rmSync(foreign,{recursive:true,force:true});}});
test('mismatched Node or npm runtime version fails closed',()=>{const f=fixture('linux');try{for(const versions of [['v22.0.0','11.19.0'],['v24.21.0','10.0.0']])assert.throws(()=>probeNodeOwnedNpm(f.node,{platform:'linux',expectedNodeVersion:'24.21.0',run:(_exe,args)=>args[0]==='--version'?versions[0]:versions[1]}));}finally{f.cleanup();}});
test('unsupported layout/platform cannot use PATH or a system npm',()=>{const f=fixture('linux');try{assert.throws(()=>resolveNodeOwnedNpm(f.node,{platform:'darwin'}));const renamed=join(f.directory,'node');writeFileSync(renamed,'controlled');assert.throws(()=>resolveNodeOwnedNpm(renamed,{platform:'linux'}));rmSync(join(f.pkg,'bin/npm-cli.js'));assert.throws(()=>probeNodeOwnedNpm(f.node,{platform:'linux',expectedNodeVersion:'24.21.0',run:()=>{throw new Error('must not probe fallback');}}));}finally{f.cleanup();}});
test('CLI directory escape is rejected even with valid owned metadata',()=>{const f=fixture('linux'),foreign=mkdtempSync(join(tmpdir(),'foreign-cli-contract-'));try{rmSync(join(f.pkg,'bin'),{recursive:true});writeFileSync(join(foreign,'npm-cli.js'),'foreign');symlinkSync(foreign,join(f.pkg,'bin'),'junction');assert.throws(()=>resolveNodeOwnedNpm(f.node,{platform:'linux'}));}finally{f.cleanup();rmSync(foreign,{recursive:true,force:true});}});
test('invalid package version cannot establish runtime identity',()=>{const f=fixture('win32');try{writeFileSync(join(f.pkg,'package.json'),JSON.stringify({name:'npm',version:'latest',bin:{npm:'bin/npm-cli.js'}}));assert.throws(()=>resolveNodeOwnedNpm(f.node,{platform:'win32'}));}finally{f.cleanup();}});
