/** Pure graph construction. Never invokes Docker, resolves credentials or authorizes release. */
export {validateApiEnvironment} from './platform-runtime-environment.ts';
type LocalInput = {authority:'synthetic-local-only';origin:string;project:string;apiImage:string;webImage:string;commit:string;database:string;runtimeRole:string;migratorRole:string;attestationKey:string;files:Record<'runtimePassword'|'migratorPassword'|'apiEnvironment'|'publicConfig'|'runtimeSource'|'webTemplate'|'tls'|'routing',string>};
const NODE_IMAGE='public.ecr.aws/docker/library/node:24.21.0-alpine@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1';
function fail():never{throw new Error('LOCAL_REHEARSAL_INPUT_INVALID');}
export function buildLocalRuntimePlan(value: unknown): any {
 const v=value as LocalInput;
 if(!v||v.authority!=='synthetic-local-only'||Object.keys(v).some(k=>!['authority','origin','project','apiImage','webImage','commit','database','runtimeRole','migratorRole','attestationKey','files'].includes(k)))fail();
 let url:URL;try{url=new URL(v.origin);}catch{return fail();}
 if(url.protocol!=='https:'||url.origin!==v.origin||!url.hostname.endsWith('.invalid')||url.username||url.password)fail();
 if(!/^platform-rehearsal(?:-[a-z0-9]{1,32})?$/.test(v.project)||!/^ghcr\.io\/tandavkrishna27\/explorers-api@sha256:[a-f0-9]{64}$/.test(v.apiImage)||!/^ghcr\.io\/tandavkrishna27\/explorers-web@sha256:[a-f0-9]{64}$/.test(v.webImage)||! /^[a-f0-9]{40}$/.test(v.commit))fail();
 for(const role of [v.database,v.runtimeRole,v.migratorRole])if(!/^[a-z_][a-z0-9_]{1,62}$/.test(role))fail();
 if(v.runtimeRole===v.migratorRole||['postgres','music_runtime'].includes(v.runtimeRole)||!v.attestationKey?.startsWith('synthetic-only-')||v.attestationKey.length<32)fail();
 const keys=['runtimePassword','migratorPassword','apiEnvironment','publicConfig','runtimeSource','webTemplate','tls','routing'];
 if(!v.files||Object.keys(v.files).length!==keys.length||keys.some(k=>typeof v.files[k as keyof LocalInput['files']]!=='string'||!/^\/(?:[A-Za-z0-9_.-]+\/)*[A-Za-z0-9_.-]+$/.test(v.files[k as keyof LocalInput['files']]))||Object.values(v.files).some(p=>p.split('/').includes('..'))||new Set(Object.values(v.files)).size!==keys.length)fail();
 const f=v.files;
 const database={MUSIC_MODE:'live',MUSIC_DATABASE_HOST:'postgres',MUSIC_DATABASE_PORT:'5432',MUSIC_DATABASE_NAME:v.database,MUSIC_DATABASE_MIGRATOR_USER:v.migratorRole};
 const common={security_opt:['no-new-privileges:true'],cap_drop:['ALL']};
 const compose:any={name:v.project,services:{
 postgres:{image:'postgres:15-alpine@sha256:fceb6f86328c36f2438fae3b851b0cc57c4a7e69a58c866d9ce24281f2cf0c9c',environment:{POSTGRES_USER:v.migratorRole,POSTGRES_DB:v.database,POSTGRES_PASSWORD_FILE:'/run/secrets/migrator'},volumes:['postgres-data:/var/lib/postgresql/data',`${f.migratorPassword}:/run/secrets/migrator:ro`],networks:['database'],healthcheck:{test:['CMD-SHELL','pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"'],interval:'3s',timeout:'3s',retries:20},restart:'unless-stopped'},
 migrate:{...common,image:v.apiImage,command:['node','dist/server/deployment/run-migration-gate.js'],restart:'no',environment:{...database,MUSIC_DATABASE_USER:v.migratorRole,MUSIC_DATABASE_PASSWORD_FILE:'/run/secrets/migrator',MUSIC_RUNTIME_DATABASE_USER:v.runtimeRole,MUSIC_RUNTIME_DATABASE_PASSWORD_FILE:'/run/secrets/runtime',MUSIC_IMAGE_DIGEST:v.apiImage.split('@')[1],MUSIC_IMAGE_COMMIT:v.commit,MUSIC_MIGRATION_MARKER:'0037_explorers_movies_provider_context',MUSIC_GATE_ATTESTATION_KEY:v.attestationKey,MUSIC_GATE_ATTESTATION_PATH:'/deployment-gates/gate.json'},volumes:[`${f.migratorPassword}:/run/secrets/migrator:ro`,`${f.runtimePassword}:/run/secrets/runtime:ro`,'gate-evidence:/deployment-gates'],networks:['database'],depends_on:{postgres:{condition:'service_healthy'}}},
 api:{...common,image:v.apiImage,command:['node','dist/server/api.js'],env_file:[{path:f.apiEnvironment,required:true}],environment:{...database,NODE_ENV:'production',EXPLORERS_API_MODE:'canonical',PORT:'5000',MUSIC_DATABASE_USER:v.runtimeRole,MUSIC_DATABASE_PASSWORD_FILE:'/run/secrets/runtime',EXPLORERS_PUBLIC_ORIGIN:v.origin,EXPLORERS_DEPLOYMENT_TIER:'qa',EXPLORERS_MEDIA_ENVIRONMENT:'qa'},volumes:[`${f.runtimePassword}:/run/secrets/runtime:ro`],networks:['database','api'],depends_on:{migrate:{condition:'service_completed_successfully'}},healthcheck:{test:['CMD','node','-e',"fetch('http://127.0.0.1:5000/health/live').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"],interval:'3s',timeout:'3s',retries:20},restart:'unless-stopped'},
 render:{...common,image:NODE_IMAGE,read_only:true,command:['node','/opt/platform-runtime/scripts/render-platform-runtime.mjs','/run/platform/public-config.json','/template/index.html','/runtime-web'],volumes:[`${f.runtimeSource}:/opt/platform-runtime:ro`,`${f.publicConfig}:/run/platform/public-config.json:ro`,`${f.webTemplate}:/template/index.html:ro`,'runtime-web:/runtime-web'],network_mode:'none',restart:'no'},
 web:{...common,cap_add:['CHOWN','SETUID','SETGID','NET_BIND_SERVICE'],image:v.webImage,volumes:['runtime-web:/runtime-web:ro'],networks:['web'],depends_on:{render:{condition:'service_completed_successfully'}},healthcheck:{test:['CMD','wget','-q','-O','/dev/null','http://127.0.0.1/'],interval:'3s',timeout:'3s',retries:20},restart:'unless-stopped'},
 proxy:{image:'traefik:v3.1@sha256:8516638b18e67e999d293e4ff0e5baf7807674cd4bdd3d36d448497bcbf0a174',command:['--api.dashboard=false','--providers.file.filename=/routing/platform-routing.yml','--entrypoints.websecure.address=:443'],ports:['127.0.0.1:0:443'],volumes:[`${f.routing}:/routing/platform-routing.yml:ro`,`${f.tls}:/tls:ro`],networks:['api','web'],depends_on:{api:{condition:'service_healthy'},web:{condition:'service_healthy'}},restart:'unless-stopped'},
 },networks:{database:{internal:true},api:{},web:{internal:true}},volumes:{'postgres-data':{},'gate-evidence':{},'runtime-web':{}}};
 const host=`Host(\`${url.hostname}\`)`;
 const router=(rule:string,service:string,priority:number)=>({rule,service,priority,entryPoints:['websecure'],tls:{},middlewares:service==='api'?['qa-policy','api-no-cache']:['qa-policy']});
 const routing={http:{routers:{api:router(`${host} && (Path(\`/api\`) || PathPrefix(\`/api/\`))`,'api',100),socket:router(`${host} && (Path(\`/socket.io\`) || PathPrefix(\`/socket.io/\`))`,'api',100),legacy:router(`${host} && (Path(\`/graphql\`) || PathPrefix(\`/graphql/\`))`,'api',100),web:router(host,'web',1)},services:{api:{loadBalancer:{passHostHeader:true,servers:[{url:'http://api:5000'}]}},web:{loadBalancer:{passHostHeader:true,servers:[{url:'http://web:80'}]}}},middlewares:{'qa-policy':{headers:{customResponseHeaders:{'X-Robots-Tag':'noindex,nofollow'}}},'api-no-cache':{headers:{customResponseHeaders:{'Cache-Control':'no-store'}}}}},tls:{certificates:[{certFile:'/tls/cert.pem',keyFile:'/tls/key.pem'}]}};
 return {version:1,authority:'synthetic-local-only',releaseQualified:false,schemaVersion:36,compose,routing,capabilities:{musicSocket:'not-delivered',forwardedClientIp:'not-qualified'},requiredPreflight:['local-daemon','protected-files','api-environment-allowlist','public-config-origin','verified-web-extraction','same-source-api-image']};
}
export function planHostedRuntime(_manifest: unknown, _readiness: unknown): never { throw new Error('TRUSTED_AUTHORITY_UNAVAILABLE'); }
