import {randomBytes} from 'node:crypto';
import type {Actor} from '../application/actor';
import {movieSearchRequestSchema,movieCandidateSchema,movieDetailsSchema,type MovieCandidate,type MovieDetails} from '../../shared/explorersMovieContract';
export class MovieProviderFailure extends Error{constructor(readonly status:410|422|429|502|503,readonly code='PROVIDER_UNAVAILABLE'){super(code==='CONTINUATION_LIMIT'?'Movie search continuation limit reached':status===503?'Movie provider unavailable':status===502?'Invalid Movie provider response':status===410?'Movie cursor expired':status===429?'Movie lookup rate limited':'Invalid Movie lookup');}}
const invalid=()=>new MovieProviderFailure(502,'PROVIDER_INVALID_RESPONSE');const fail=()=>new MovieProviderFailure(503);const cloned=<T>(x:T):T=>structuredClone(x);const bytes=(x:unknown)=>Buffer.byteLength(JSON.stringify(x));
const image=(v:unknown,size:string):string|null=>{if(v===null||v===undefined||v==='')return null;if(typeof v!=='string'||!/^\/[A-Za-z0-9_.-]{1,200}$/.test(v))throw invalid();return `https://image.tmdb.org/t/p/${size}${v}`;};
// Validate duplicate escaped keys before materialization; bounds are independent of release JSON contracts.
function providerJson(text:string):unknown{
 if(Buffer.byteLength(text,'utf8')>2097152)throw invalid();let i=0,nodes=0;
 const ws=()=>{while(/[\t\n\r ]/.test(text[i]??'!'))i++;};
 const string=():string=>{const start=i++;while(i<text.length){const c=text[i++];if(c==='"'){try{return JSON.parse(text.slice(start,i));}catch{throw invalid();}}if(c==='\\')i++;}throw invalid();};
 const value=(depth:number):void=>{if(++nodes>10000||depth>16)throw invalid();ws();if(text[i]==='{'){i++;ws();const keys=new Set<string>();if(text[i]!=='}')while(true){if(text[i]!=='"')throw invalid();const key=string();if(keys.has(key))throw invalid();keys.add(key);ws();if(text[i++]!==':')throw invalid();value(depth+1);ws();if(text[i]!==',')break;i++;ws();}if(text[i++]!=='}')throw invalid();}else if(text[i]==='['){i++;ws();if(text[i]!==']')while(true){value(depth+1);ws();if(text[i]!==',')break;i++;}if(text[i++]!==']')throw invalid();}else if(text[i]==='"'){if(string().length>100000)throw invalid();}else{const match=/^(?:true|false|null|-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)/.exec(text.slice(i));if(!match)throw invalid();i+=match[0].length;}};
 value(0);ws();if(i!==text.length)throw invalid();try{return JSON.parse(text);}catch{throw invalid();}
}
const clean=(v:unknown,n=1000):string|null=>{if(v===null||v===undefined)return null;if(typeof v!=='string'||v.length>n||!v.isWellFormed()||/[\u0000-\u001f\u007f]/.test(v))throw invalid();return v.trim();};
const number=(v:unknown,max=2147483647):number|null=>{if(v==null)return null;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)throw invalid();return v;};
function candidate(raw:any,kind:'movie'|'tv'):MovieCandidate{try{return movieCandidateSchema.parse({provider:'tmdb',externalKind:kind,externalId:String(raw.id),title:clean(kind==='movie'?raw.title:raw.name),posterUrl:image(raw.poster_path,'w342'),yearText:clean(kind==='movie'?raw.release_date:raw.first_air_date,100)?.match(/^\d{4}/)?.[0]??null});}catch{throw invalid();}}
export function mapMovieDetail(raw:any,kind:'movie'|'tv',expectedId:string,fetchedAt:number,watch:any){
 if(!raw||String(raw.id)!==expectedId)throw invalid();const base=candidate(raw,kind);if(base.title.length>500)throw invalid();const regions:Record<string,any>={};
 if(!watch||typeof watch!=='object'||Array.isArray(watch)||Object.keys(watch).length>32)throw invalid();
 for(const [key,r]of Object.entries(watch) as [string,any][]){if(!/^[A-Z]{2}$/.test(key)||!r||typeof r!=='object')throw invalid();const facts:any={link:r.link??null};for(const mode of ['flatrate','rent','buy']){const arr=r[mode]??[];if(!Array.isArray(arr)||arr.length>64)throw invalid();facts[mode]=arr.map((p:any)=>({providerId:p.provider_id,name:p.provider_name,logoUrl:image(p.logo_path,'w92'),priority:p.display_priority}));}regions[key]=facts;}
 if(!Array.isArray(raw.genres)||raw.genres.length>32||raw.credits?.cast&&!Array.isArray(raw.credits.cast)||raw.credits?.cast?.length>200||raw.credits?.crew&&!Array.isArray(raw.credits.crew)||raw.credits?.crew?.length>500)throw invalid();
 let details:MovieDetails;try{details=movieDetailsSchema.parse({mediaType:kind,originalTitle:clean(kind==='movie'?raw.original_title:raw.original_name),yearText:base.yearText,posterUrl:image(raw.poster_path,'w780'),backdropUrl:image(raw.backdrop_path,'w1280'),genres:raw.genres.map((g:any)=>({providerGenreId:g.id,name:g.name})),director:kind==='movie'?clean(raw.credits?.crew?.find((x:any)=>x.job==='Director')?.name):null,runtimeMinutes:kind==='movie'?number(raw.runtime):number(raw.episode_run_time?.[0]),providerRating:number(raw.vote_average,10),overview:clean(raw.overview,100000),seasonCount:kind==='tv'?number(raw.number_of_seasons):null,watchProviders:regions,cast:(raw.credits?.cast??[]).map((p:any)=>({personId:p.id,creditId:p.credit_id,name:p.original_name??p.name,character:p.character??'',profileUrl:image(p.profile_path,'w185'),order:p.order}))});}catch{throw invalid();}
 if(bytes(details)>1048576)throw invalid();
 return {...base,details,provenance:{provider:'tmdb' as const,externalKind:kind,externalId:expectedId,fetchedAt,sourceUrl:`https://api.themoviedb.org/3/${kind}/${expectedId}`,mappingVersion:1 as const}};
}
type Kind='movie'|'tv';type Lineage={attempts:number;scans:number};type State={account:string;query:string;mode?:Kind;limit:number;expires:number;turn:Kind;pending:Record<Kind,MovieCandidate[]>;page:Record<Kind,number>;done:Record<Kind,boolean>;seen:string[];emitted:number;lineage:Lineage};type Result={version:'explorers-movie-candidates/v1';items:MovieCandidate[];nextCursor:string|null;expiresAt:number};type Entry={state:State;response?:Result;flight?:Promise<Result>;size:number;pins?:number};
type Lease={pending:number;finished:boolean;release:()=>void};
type Options={accessToken?:string;apiKey?:string;fetch?:typeof fetch;now?:()=>number;deadlineMs?:number;authorize:(a:Actor)=>Promise<void>};
/** Production caller supplies the real Actor revalidation seam, including cached replay. */
export class MovieCatalog{
 private readonly states=new Map<string,Entry>();private readonly rates=new Map<string,{since:number;count:number}>();private readonly accountFlights=new Set<string>();private used=0;private inflight=0;private active=0;private readonly fetcher:typeof fetch;private readonly now:()=>number;
 constructor(private readonly options:Options){this.fetcher=options.fetch??fetch;this.now=options.now??Date.now;}
 private async bounded<T>(job:Promise<T>,signal:AbortSignal):Promise<T>{if(signal.aborted)throw fail();let reject:(e:Error)=>void=()=>{};const abort=()=>reject(fail());const timer=new Promise<never>((_,r)=>{reject=r;signal.addEventListener('abort',abort,{once:true});});try{return await Promise.race([job,timer]);}finally{signal.removeEventListener('abort',abort);}}
 private rate(account:string){const now=this.now();for(const [k,r]of Array.from(this.rates))if(now-r.since>=60000)this.rates.delete(k);const r=this.rates.get(account)??{since:now,count:0};if(r.count>=30||this.rates.size>=10000&&!this.rates.has(account))throw new MovieProviderFailure(429,'RATE_LIMITED');r.count++;this.rates.set(account,r);}
 private touch(key:string,entry:Entry){this.states.delete(key);this.states.set(key,entry);}
 private room(size:number,account:string,extra=1){
 for(const [key,e]of Array.from(this.states))if(e.state.expires<=this.now()&&!e.flight&&!e.pins){this.states.delete(key);this.used-=e.size;}
 const count=()=>Array.from(this.states.values()).filter(e=>e.state.account===account).length;
 while(this.states.size+extra>200||count()+extra>20||this.used+this.inflight+size>4194304){const accountFull=count()+extra>20;const victim=Array.from(this.states).find(([,e])=>!e.flight&&!e.pins&&(!accountFull||e.state.account===account));if(!victim)throw new MovieProviderFailure(429,'RATE_LIMITED');this.states.delete(victim[0]);this.used-=victim[1].size;}
 }
 private own<T>(lease:Lease,job:Promise<T>):Promise<T>{lease.pending++;const settled=()=>{lease.pending--;if(lease.finished&&lease.pending===0)lease.release();};void job.then(settled,settled);return job;}
 private finish(lease:Lease){lease.finished=true;if(lease.pending===0)lease.release();}
 private async request(actor:Actor,path:string,params:URLSearchParams,pageSignal:AbortSignal,lineage:Lineage,budget:{bytes:number;retained:number},lease:Lease):Promise<any>{
 if(!this.options.accessToken&&!this.options.apiKey)throw fail();if(++lineage.attempts>52)throw new MovieProviderFailure(429,'CONTINUATION_LIMIT');await this.bounded(this.options.authorize(actor),pageSignal);const signal=AbortSignal.any([pageSignal,AbortSignal.timeout(5000)]);const url=new URL(`https://api.themoviedb.org/3/${path}`);url.search=params.toString();if(!this.options.accessToken)url.searchParams.set('api_key',this.options.apiKey!);
 const work=(async()=>{const response=await this.own(lease,Promise.resolve().then(()=>this.fetcher(url,{redirect:'error',signal,headers:this.options.accessToken?{Authorization:`Bearer ${this.options.accessToken}`}:{}})));const discard=()=>{if(response.body)try{this.own(lease,response.body.cancel());}catch{}};if(signal.aborted){discard();throw fail();}if(response.status===429){discard();throw new MovieProviderFailure(429,'RATE_LIMITED');}if(!response.ok){discard();throw fail();}if(Number(response.headers.get('content-length'))>2097152){discard();throw invalid();}const reader=response.body?.getReader();if(!reader)throw invalid();const chunks:Uint8Array[]=[];let size=0;let cancelled=false;const cancel=()=>{if(cancelled)return;cancelled=true;try{this.own(lease,reader.cancel());}catch{}};signal.addEventListener('abort',cancel,{once:true});try{while(true){const part=await this.bounded(this.own(lease,reader.read()),signal);if(part.done)break;size+=part.value.byteLength;budget.bytes+=part.value.byteLength;if(size>2097152||budget.bytes>8388608)throw invalid();this.room(part.value.byteLength,actor.accountId,0);this.inflight+=part.value.byteLength;budget.retained+=part.value.byteLength;chunks.push(part.value);}let body:any;try{body=providerJson(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks)));}catch{throw invalid();}const queue=[{v:body,d:0}];let nodes=0;while(queue.length){const {v,d}=queue.pop()!;if(++nodes>10000||d>16||typeof v==='string'&&v.length>100000)throw invalid();if(v&&typeof v==='object')for(const value of Object.values(v))queue.push({v:value,d:d+1});}return body;}finally{signal.removeEventListener('abort',cancel);cancel();try{reader.releaseLock();}catch{}}})();return this.bounded(this.own(lease,work),signal);
 }
 async search(actor:Actor,raw:unknown):Promise<Result>{const parsed=movieSearchRequestSchema.safeParse(raw);if(!parsed.success)throw new MovieProviderFailure(422,'INVALID_INPUT');const p=parsed.data;const signal=AbortSignal.timeout(this.options.deadlineMs??10000);await this.bounded(this.options.authorize(actor),signal);this.rate(actor.accountId);let entry:Entry|undefined;
 if(p.cursor){entry=this.states.get(p.cursor);if(!entry||entry.state.expires<=this.now()||entry.state.account!==actor.accountId||entry.state.query!==p.query||entry.state.limit!==p.limit||entry.state.mode!==p.mediaType)throw new MovieProviderFailure(410,'CURSOR_EXPIRED');this.touch(p.cursor,entry);if(entry.response){entry.pins=(entry.pins??0)+1;try{await this.bounded(this.options.authorize(actor),signal);return cloned(entry.response);}finally{entry.pins!--;}}if(entry.flight){const r=await this.bounded(entry.flight,signal);await this.bounded(this.options.authorize(actor),signal);return cloned(r);}}
 if(this.accountFlights.has(actor.accountId)||this.active>=4)throw new MovieProviderFailure(429,'RATE_LIMITED');if(entry)entry.pins=(entry.pins??0)+1;try{this.room(262144,actor.accountId,0);}catch(error){if(entry)entry.pins!--;throw error;}this.inflight+=262144;let reserved=262144;this.active++;this.accountFlights.add(actor.accountId);
 const initial:State=entry?.state??{account:actor.accountId,query:p.query,mode:p.mediaType,limit:p.limit,expires:this.now()+600000,turn:p.mediaType??'movie',pending:{movie:[],tv:[]},page:{movie:1,tv:1},done:{movie:p.mediaType==='tv',tv:p.mediaType==='movie'},seen:[],emitted:0,lineage:{attempts:0,scans:0}};
 const budget={bytes:0,retained:0};let released=false;const lease:Lease={pending:0,finished:false,release:()=>{if(released)return;released=true;this.inflight-=reserved+budget.retained;this.active--;this.accountFlights.delete(actor.accountId);if(entry)entry.pins!--;}};const execute=async():Promise<Result>=>{const next=cloned(initial);next.lineage=initial.lineage;const items:MovieCandidate[]=[];const reserve=()=>{const needed=Math.max(262144,bytes(next)+bytes(items)+256);if(needed>reserved){this.room(needed-reserved,actor.accountId,0);this.inflight+=needed-reserved;reserved=needed;}};reserve();const fill=async(kind:Kind)=>{if(next.pending[kind].length||next.done[kind])return;const page=next.page[kind];if(page>500){next.done[kind]=true;return;}const b=await this.request(actor,`search/${kind}`,new URLSearchParams({query:p.query,page:String(page),language:'en-US',include_adult:'false'}),signal,next.lineage,budget,lease);if(Array.isArray(b?.results)){next.lineage.scans+=b.results.length;if(next.lineage.scans>5200)throw new MovieProviderFailure(429,'CONTINUATION_LIMIT');}if(!b||b.page!==page||!Number.isSafeInteger(b.total_pages)||b.total_pages<0||!Number.isSafeInteger(b.total_results)||b.total_results<0||!Array.isArray(b.results)||b.results.length>100||b.results.length===0&&page<b.total_pages)throw invalid();next.pending[kind]=b.results.map((r:any)=>candidate(r,kind));next.page[kind]++;next.done[kind]=page>=b.total_pages||page===500;reserve();};
 // Fetch both first sources before committing any partial result.
 await fill('movie');await fill('tv');while(items.length<p.limit){if(next.emitted>=500){if(!next.pending.movie.length&&!next.pending.tv.length&&next.done.movie&&next.done.tv)break;throw new MovieProviderFailure(429,'CONTINUATION_LIMIT');}const k=next.turn;await fill(k);const other:Kind=k==='movie'?'tv':'movie';await fill(other);const use=next.pending[k].length?k:other;if(!next.pending[use].length)break;const value=next.pending[use].shift()!;next.turn=use==='movie'?'tv':'movie';const identity=`${value.externalKind}:${value.externalId}`;if(next.seen.includes(identity))continue;next.seen.push(identity);next.emitted++;items.push(value);reserve();}
 await this.bounded(this.options.authorize(actor),signal);if(next.expires<=this.now())throw new MovieProviderFailure(410,'CURSOR_EXPIRED');const more=next.pending.movie.length||next.pending.tv.length||!next.done.movie||!next.done.tv;const token=more?randomBytes(24).toString('base64url'):null;const response:Result={version:'explorers-movie-candidates/v1',items,nextCursor:token,expiresAt:next.expires};const nextEntry:Entry={state:next,size:bytes(next)+128};const responseSize=bytes(response);this.room((token?nextEntry.size:0)+responseSize,actor.accountId,token?1:0);if(token){this.states.set(token,nextEntry);this.used+=nextEntry.size;}if(entry){entry.response=cloned(response);entry.size+=responseSize;this.used+=responseSize;}return cloned(response);};
 const job=this.own(lease,execute());if(entry)entry.flight=job;try{const result=await this.bounded(job,signal);await this.bounded(this.options.authorize(actor),signal);return result;}finally{if(entry)entry.flight=undefined;this.finish(lease);}
 }
 async resolve(actor:Actor,kind:Kind,id:string){if(!/^[1-9]\d{0,15}$/.test(id)||!Number.isSafeInteger(Number(id))||!['movie','tv'].includes(kind))throw new MovieProviderFailure(422,'INVALID_INPUT');const signal=AbortSignal.timeout(this.options.deadlineMs??10000);await this.bounded(this.options.authorize(actor),signal);this.rate(actor.accountId);if(this.accountFlights.has(actor.accountId)||this.active>=4)throw new MovieProviderFailure(429,'RATE_LIMITED');this.room(262144,actor.accountId,0);this.inflight+=262144;const budget={bytes:0,retained:0},lineage={attempts:0,scans:0};let released=false;const lease:Lease={pending:0,finished:false,release:()=>{if(released)return;released=true;this.inflight-=262144+budget.retained;this.active--;this.accountFlights.delete(actor.accountId);}};this.accountFlights.add(actor.accountId);this.active++;try{const raw=await this.request(actor,`${kind}/${id}`,new URLSearchParams({language:'en-US',append_to_response:'credits'}),signal,lineage,budget,lease);const watch=await this.request(actor,`${kind}/${id}/watch/providers`,new URLSearchParams(),signal,lineage,budget,lease);if(String(watch.id)!==id)throw invalid();const result=mapMovieDetail(raw,kind,id,this.now(),watch.results??{});const mappedBytes=bytes(result);this.room(mappedBytes,actor.accountId,0);this.inflight+=mappedBytes;budget.retained+=mappedBytes;await this.bounded(this.options.authorize(actor),signal);return result;}finally{this.finish(lease);}}
}
