import {it,expect} from 'vitest';import {readFileSync} from 'node:fs';
it('Movies0037 preserves canonical taxonomy, composite ownership and destination-context guards',()=>{const sql=readFileSync(new URL('../../../migrations/0037_explorers_movies_provider_context.sql',import.meta.url),'utf8');for(const name of ['movie_entity_details','movie_entity_provider_genres','taxonomy_terms','taxonomy_term_translations','movie_provider_genre_terms','recommendation_taxonomy','movie_recommendation_context'])expect(sql).toContain(`CREATE TABLE public.${name}`);expect(sql).toMatch(/REFERENCES public\.recommendations\(id,account_id,category\)/);expect(sql).toMatch(/REFERENCES public\.taxonomy_terms\(id,category\)/);expect(sql).toContain('guard_movie_context');expect(sql).toContain('FOR UPDATE');expect(sql).toContain('selected_provider_ids');expect(sql).toContain('WITH RECURSIVE');expect(sql).not.toContain('taxonomy_terms.label');});

import {effectiveMovieWatchOffers} from '../../explorers/categories/movies';
import {emptyMovieDetails} from '../../../shared/explorersMovieContract';
it('derives defaultUS watch offers with mode precedence, priority order and explicit clear',()=>{const d=emptyMovieDetails();const offer=(id:number,priority=0)=>({providerId:id,name:'P'+id,logoUrl:null,priority});d.watchProviders={US:{link:null,flatrate:[offer(2,2),offer(1,1)],rent:[offer(1,0),offer(3,0)],buy:[offer(4,0)]},GB:{link:null,flatrate:[offer(9)],rent:[],buy:[]}};expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:null}).map(x=>x.providerId)).toEqual([3,4,1,2]);expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:[]})).toEqual([]);expect(effectiveMovieWatchOffers(d,{region:'GB',selectedProviderIds:[9]}).map(x=>x.providerId)).toEqual([9]);expect(()=>effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:[9]})).toThrow('MOVIE_CONTEXT_INCOMPATIBLE');});

it('keeps the original first duplicate within a mode before any priority sorting',()=>{const d=emptyMovieDetails();d.watchProviders={US:{link:null,flatrate:[{providerId:7,name:'First',logoUrl:null,priority:9},{providerId:7,name:'Later',logoUrl:null,priority:0}],rent:[],buy:[]}};expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:null})).toEqual([{providerId:7,name:'First',logoUrl:null,priority:9}]);});
it('retains stable source order for equal priorities and explicit owner selection order',()=>{const d=emptyMovieDetails();const offer=(id:number)=>({providerId:id,name:'P'+id,logoUrl:null,priority:1});d.watchProviders={US:{link:null,flatrate:[offer(9),offer(2)],rent:[offer(8)],buy:[offer(1)]}};expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:null}).map(p=>p.providerId)).toEqual([9,2,8,1]);expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:[1,9,8]}).map(p=>p.providerId)).toEqual([1,9,8]);});
it('takes default eight after cross-mode first-ID dedup and global stable priority ordering',()=>{const d=emptyMovieDetails();const offer=(id:number,priority:number)=>({providerId:id,name:'P'+id,logoUrl:null,priority});d.watchProviders={US:{link:null,flatrate:Array.from({length:8},(_,i)=>offer(i+1,10+i)),rent:[offer(1,0),offer(9,1),offer(10,2)],buy:[offer(11,0)]}};expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:null}).map(p=>p.providerId)).toEqual([11,9,10,1,2,3,4,5]);expect(effectiveMovieWatchOffers(d,{region:'US',selectedProviderIds:[8,11,1]}).map(p=>p.providerId)).toEqual([8,11,1]);});
